package niri

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestMain pins HOME (which the template loader's override base derives from)
// and XDG_CONFIG_HOME to a temp dir so tests render the embedded templates
// rather than any user overrides in ~/.config/tinct/templates.
func TestMain(m *testing.M) {
	dir, err := os.MkdirTemp("", "tinct-niri-test-home")
	if err != nil {
		panic(err)
	}
	os.Setenv("HOME", dir)
	os.Setenv("XDG_CONFIG_HOME", filepath.Join(dir, ".config"))
	code := m.Run()
	_ = os.RemoveAll(dir)
	os.Exit(code)
}

// TestNiriPlugin runs all standard plugin tests using shared utilities.
func TestNiriPlugin(t *testing.T) {
	plugin := New()

	t.Run("Name", func(t *testing.T) {
		if plugin.Name() != "niri" {
			t.Errorf("Name() = %s, want niri", plugin.Name())
		}
	})

	t.Run("Description", func(t *testing.T) {
		if plugin.Description() == "" {
			t.Error("Description() should not be empty")
		}
	})

	t.Run("DefaultOutputDir", func(t *testing.T) {
		dir := plugin.DefaultOutputDir()
		if dir == "" {
			t.Error("DefaultOutputDir() should not be empty")
		}
		if !strings.Contains(dir, "niri") {
			t.Errorf("DefaultOutputDir() = %s, should contain 'niri'", dir)
		}
	})

	expectedFiles := []string{"tinct-colours.kdl", "tinct.kdl"}

	plugintesting.TestGeneration(t, plugin, expectedFiles)
	plugintesting.TestPreExecuteHook(t, plugin, "niri")
	plugintesting.TestFlags(t, plugin, "niri")
}

// TestNiriPlugin_ContentValidation tests niri-specific content requirements.
func TestNiriPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-colours.kdl"])

	requiredStrings := []string{
		"niri colour theme generated by Tinct",
		"focus-ring",
		"active-gradient",
		"tab-indicator",
		"overview",
		"backdrop-color",
		"Detected theme: dark",
	}
	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}

	// Colours must render as #rrggbb hex strings, not empty templates.
	if !strings.Contains(content, "active-color \"#") {
		t.Error("Generated content missing hex colour values")
	}
	if strings.Contains(content, "\"#\"") {
		t.Error("Generated content contains empty hex colour - templating failed")
	}
}

// TestNiriPlugin_GenerateWithLightTheme tests light theme generation.
func TestNiriPlugin_GenerateWithLightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-colours.kdl"])
	if !strings.Contains(content, "Detected theme: light") {
		t.Error("Generated content missing light theme type")
	}
}

// TestNiriPlugin_GenerateWithStub tests stub file generation with a custom path.
func TestNiriPlugin_GenerateWithStub(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()
	plugin.generateStub = true
	plugin.stubPath = "custom-niri.kdl"

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if len(files) != 2 {
		t.Fatalf("Generate() with stub returned %d files, want 2", len(files))
	}
	if _, ok := files["tinct-colours.kdl"]; !ok {
		t.Error("Generate() did not return tinct-colours.kdl")
	}

	stubFile := filepath.Base(plugin.stubPath)
	stub, ok := files[stubFile]
	if !ok {
		t.Fatalf("Generate() did not return stub file %s", stubFile)
	}
	if !strings.Contains(string(stub), "include") {
		t.Error("Stub file should document the include directive")
	}
}

// TestNiriPlugin_GenerateWithoutStub tests generation without the stub file.
func TestNiriPlugin_GenerateWithoutStub(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()
	plugin.generateStub = false

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("Generate() without stub returned %d files, want 1", len(files))
	}
	if _, ok := files["tinct-colours.kdl"]; !ok {
		t.Error("Generate() should still return tinct-colours.kdl")
	}
	if _, ok := files["tinct.kdl"]; ok {
		t.Error("Generate() should not return tinct.kdl when generateStub is false")
	}
}

// TestNiriPlugin_CustomOutputDir tests custom output directory handling.
func TestNiriPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestNiriPlugin_GetEmbeddedTemplates tests embedded template access.
func TestNiriPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	foundColours := false
	foundStub := false
	for _, entry := range entries {
		switch entry.Name() {
		case "tinct-colours.kdl.tmpl":
			foundColours = true
		case "tinct.kdl.tmpl":
			foundStub = true
		}
	}

	if !foundColours {
		t.Error("Template tinct-colours.kdl.tmpl not found in embedded filesystem")
	}
	if !foundStub {
		t.Error("Template tinct.kdl.tmpl not found in embedded filesystem")
	}
}
