package kitty

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestKittyPlugin runs all standard plugin tests using shared utilities.
func TestKittyPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "kitty",
		ExpectedFiles:      []string{"tinct.conf"},
		ExpectedBinaryName: "kitty",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestKittyPlugin_ContentValidation tests kitty-specific content requirements.
func TestKittyPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct.conf"])

	// Check for required sections
	requiredStrings := []string{
		"# Kitty colour theme generated by Tinct",
		"foreground",
		"background",
		"cursor",
		"active_tab_background",
		"inactive_tab_background",
		"color0",
		"color15",
		"# accent1",
		"# background",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: dark") {
		t.Error("Generated content missing theme type")
	}
}

// TestKittyPlugin_GenerateWithLightTheme tests light theme generation.
func TestKittyPlugin_GenerateWithLightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct.conf"])

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: light") {
		t.Error("Generated content missing light theme type")
	}
}

// TestKittyPlugin_CustomOutputDir tests custom output directory handling.
func TestKittyPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestKittyPlugin_GetEmbeddedTemplates tests embedded template access.
func TestKittyPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	found := false
	for _, entry := range entries {
		if entry.Name() == "tinct.conf.tmpl" {
			found = true
			break
		}
	}

	if !found {
		t.Error("Template file tinct.conf.tmpl not found in embedded filesystem")
	}
}
