package wbg

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestWbgPlugin runs all standard plugin tests using shared utilities.
func TestWbgPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:         "wbg",
		ExpectedFiles:        []string{"tinct-wbg.sh"},
		ExpectedBinaryName:   "wbg",
		ExpectedDirSubstring: "wbg",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestWbgPlugin_ContentValidation tests wbg-specific content requirements.
func TestWbgPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-wbg.sh"])

	// Check for required content.
	requiredStrings := []string{
		"#!/bin/sh",
		"wbg wallpaper configuration generated by Tinct",
		"wbg",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}
}

// TestWbgPlugin_ContentWithWallpaper tests content when a wallpaper path is provided.
func TestWbgPlugin_ContentWithWallpaper(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "/home/user/wallpaper.jpg", "/home/user/wallpaper.jpg", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-wbg.sh"])

	// Check for wallpaper-specific content.
	requiredStrings := []string{
		"/home/user/wallpaper.jpg",
		"TINCT_WBG_WALLPAPER=",
		"killall wbg",
		"exec wbg",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content with wallpaper missing required string: %s", required)
		}
	}
}

// TestWbgPlugin_LightTheme tests generation with a light theme.
func TestWbgPlugin_LightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if len(files) == 0 {
		t.Error("Generate() returned no files for light theme")
	}
}
