package ptyxis

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestGenerateDualTheme verifies that when both a primary and an alternate
// theme are supplied, the plugin emits a single tinct.palette file with
// distinct [Light] and [Dark] sections (Shape B per Ptyxis source —
// ptyxis_palette_new_from_file in src/ptyxis-palette.c).
func TestGenerateDualTheme(t *testing.T) {
	darkPalette := plugintesting.CreateTestPalette(colour.ThemeDark)
	lightPalette := plugintesting.CreateTestPalette(colour.ThemeLight)

	darkTheme := colour.NewThemeData(darkPalette, "", "", "")
	lightTheme := colour.NewThemeData(lightPalette, "", "", "")

	plugin := New()

	files, err := plugin.GenerateDualTheme(darkTheme, lightTheme)
	if err != nil {
		t.Fatalf("GenerateDualTheme() error = %v", err)
	}

	if len(files) != 1 {
		t.Fatalf("Expected 1 file (tinct.palette), got %d", len(files))
	}

	content, ok := files["tinct.palette"]
	if !ok {
		t.Fatal("Missing tinct.palette in output")
	}
	s := string(content)

	requiredStrings := []string{
		"# Ptyxis colour palette generated by Tinct",
		"[Palette]",
		"Name=Tinct",
		"[Light]",
		"[Dark]",
	}
	for _, req := range requiredStrings {
		if !strings.Contains(s, req) {
			t.Errorf("dual-theme output missing %q", req)
		}
	}

	// Ptyxis requires both [Light] and [Dark] when either is present, so check
	// ordering: [Palette] header first, then [Light], then [Dark].
	palettePos := strings.Index(s, "[Palette]")
	lightPos := strings.Index(s, "[Light]")
	darkPos := strings.Index(s, "[Dark]")
	if palettePos < 0 || lightPos < 0 || darkPos < 0 {
		t.Fatalf("section markers not all found: palette=%d light=%d dark=%d", palettePos, lightPos, darkPos)
	}
	if palettePos >= lightPos || lightPos >= darkPos {
		t.Errorf("section order wrong: palette=%d light=%d dark=%d", palettePos, lightPos, darkPos)
	}

	lightSection := s[lightPos:darkPos]
	darkSection := s[darkPos:]

	for _, key := range []string{"Foreground=", "Background=", "Color0=", "Color15="} {
		if !strings.Contains(lightSection, key) {
			t.Errorf("[Light] section missing %q", key)
		}
		if !strings.Contains(darkSection, key) {
			t.Errorf("[Dark] section missing %q", key)
		}
	}

	lightBg := extractBackground(lightSection)
	darkBg := extractBackground(darkSection)
	if lightBg == "" || darkBg == "" {
		t.Fatalf("could not parse Background from sections (light=%q dark=%q)", lightBg, darkBg)
	}
	if lightBg == darkBg {
		t.Errorf("light and dark sections have identical Background %q — dual-theme should emit distinct values", lightBg)
	}
}

// TestGenerateDualThemeNilArgs checks that nil inputs produce errors rather
// than emitting half-formed palettes that Ptyxis would later reject.
func TestGenerateDualThemeNilArgs(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	theme := colour.NewThemeData(palette, "", "", "")

	plugin := New()

	if _, err := plugin.GenerateDualTheme(nil, theme); err == nil {
		t.Error("expected error with nil primary, got nil")
	}
	if _, err := plugin.GenerateDualTheme(theme, nil); err == nil {
		t.Error("expected error with nil alternate, got nil")
	}
}

// TestGenerateDualThemeOrdering verifies that whichever theme is "primary"
// (dark or light), the [Light] section ends up holding the light palette and
// [Dark] holds the dark palette — Ptyxis reads them by section name, not by
// declaration order.
func TestGenerateDualThemeOrdering(t *testing.T) {
	darkPalette := plugintesting.CreateTestPalette(colour.ThemeDark)
	lightPalette := plugintesting.CreateTestPalette(colour.ThemeLight)

	darkTheme := colour.NewThemeData(darkPalette, "", "", "")
	lightTheme := colour.NewThemeData(lightPalette, "", "", "")

	plugin := New()

	// primary=light, alternate=dark
	files, err := plugin.GenerateDualTheme(lightTheme, darkTheme)
	if err != nil {
		t.Fatalf("GenerateDualTheme(light, dark) error = %v", err)
	}
	contentA := string(files["tinct.palette"])

	// primary=dark, alternate=light
	files, err = plugin.GenerateDualTheme(darkTheme, lightTheme)
	if err != nil {
		t.Fatalf("GenerateDualTheme(dark, light) error = %v", err)
	}
	contentB := string(files["tinct.palette"])

	// Section assignment must be invariant under primary/alternate swap.
	lightBgA := extractBackground(sectionBetween(contentA, "[Light]", "[Dark]"))
	lightBgB := extractBackground(sectionBetween(contentB, "[Light]", "[Dark]"))
	if lightBgA != lightBgB {
		t.Errorf("[Light] Background changed under primary/alternate swap: %q vs %q", lightBgA, lightBgB)
	}
}

// extractBackground returns the Background= value on its first occurrence
// inside section, or "" if absent.
func extractBackground(section string) string {
	_, after, ok := strings.Cut(section, "Background=")
	if !ok {
		return ""
	}
	value, _, _ := strings.Cut(after, "\n")
	return strings.TrimSpace(value)
}

// sectionBetween returns the substring of s starting at marker `start` and
// ending at marker `end` (or end-of-string if `end` is absent).
func sectionBetween(s, start, end string) string {
	_, after, ok := strings.Cut(s, start)
	if !ok {
		return ""
	}
	body := start + after
	before, _, ok := strings.Cut(body, end)
	if !ok {
		return body
	}
	return before
}
