package ptyxis

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestPtyxisPlugin runs all standard plugin tests using shared utilities.
func TestPtyxisPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "ptyxis",
		ExpectedFiles:      []string{"tinct.palette"},
		ExpectedBinaryName: "ptyxis",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestPtyxisPlugin_ContentValidation tests ptyxis-specific content requirements.
func TestPtyxisPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct.palette"])

	// Check for required INI sections and keys.
	requiredStrings := []string{
		"# Ptyxis colour palette generated by Tinct",
		"[Palette]",
		"Name=Tinct",
		"Background=",
		"Foreground=",
		"Cursor=",
		"Color0=",
		"Color1=",
		"Color2=",
		"Color3=",
		"Color4=",
		"Color5=",
		"Color6=",
		"Color7=",
		"Color8=",
		"Color9=",
		"Color10=",
		"Color11=",
		"Color12=",
		"Color13=",
		"Color14=",
		"Color15=",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}
}

// TestPtyxisPlugin_CustomOutputDir tests custom output directory handling.
func TestPtyxisPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestPtyxisPlugin_GetEmbeddedTemplates tests embedded template access.
func TestPtyxisPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	found := false
	for _, entry := range entries {
		if entry.Name() == "tinct.palette.tmpl" {
			found = true
			break
		}
	}

	if !found {
		t.Error("Template file tinct.palette.tmpl not found in embedded filesystem")
	}
}
