# golangci-lint configuration for Tinct
# https://golangci-lint.run/usage/configuration/

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

  # Go version to target
  go: "1.25"

  # Allow multiple parallel golangci-lint instances
  allow-parallel-runners: true

# Output configuration
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  formats:
    - format: colored-line-number

  # Print lines of code with issue
  print-issued-lines: true

  # Print linter name in the end of issue text
  print-linter-name: true

  # Make issues output unique by line
  uniq-by-line: true

  # Sort results by: filepath, line and column
  sort-results: true

# Linters configuration
linters:
  # Disable all linters by default
  disable-all: true

  # Enable specific linters
  enable:
    # Bugs and correctness
    - errcheck        # Check for unchecked errors
    - gosimple        # Simplify code
    - govet           # Reports suspicious constructs
    - ineffassign     # Detect ineffectual assignments
    - staticcheck     # Go static analysis
    - typecheck       # Type-check Go code
    - unused          # Check for unused constants, variables, functions and types

    # Style and formatting
    - gofmt           # Check if code is formatted with gofmt
    - goimports       # Check if imports are formatted with goimports
    - misspell        # Find commonly misspelled English words
    - whitespace      # Check for trailing whitespace

    # Complexity
    - gocyclo         # Check cyclomatic complexity
    - gocognit        # Check cognitive complexity
    - nestif          # Check deeply nested if statements

    # Performance
    - prealloc        # Find slice declarations that could potentially be preallocated

    # Best practices
    - errname         # Check error naming conventions
    - errorlint       # Find code that will cause problems with the error wrapping
    - goconst         # Find repeated strings that could be replaced by a constant
    - gocritic        # The most opinionated Go linter
    - goprintffuncname # Check printf-like functions are named with f at the end
    - nolintlint      # Ensure nolint directives are properly used
    - revive          # Fast, configurable, extensible, flexible, and beautiful linter
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Find unused function parameters

    # Security
    - gosec           # Security problems

    # Comments and documentation
    - godot           # Check if comments end in a period

    # Modern Go features
    - gomoddirectives # Manage replace, retract directives in go.mod
    - gomodguard      # Check for blocked dependencies

    # Testing
    - tparallel       # Detects inappropriate usage of t.Parallel()

    # Error handling
    - wrapcheck       # Check that errors from external packages are wrapped

# Linters settings
linters-settings:
  # Error checking
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (*database/sql.Rows).Close
      - (*github.com/spf13/cobra.Command).MarkFlagRequired

  # Cyclomatic complexity
  gocyclo:
    min-complexity: 15

  # Cognitive complexity
  gocognit:
    min-complexity: 20

  # Constants detection
  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  # Go critic
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  # Import formatting
  goimports:
    local-prefixes: github.com/jmylchreest/tinct

  # Security
  gosec:
    excludes:
      - G104 # Audit errors not checked (covered by errcheck)
    config:
      global:
        audit: true

  # Nested if depth
  nestif:
    min-complexity: 5

  # Revive configuration
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  # Static check
  staticcheck:
    checks:
      - all
      - -SA1019 # Allow deprecated packages (we'll handle these explicitly)

  # Unused code
  unused:
    check-exported: false

  # Whitespace
  whitespace:
    multi-if: true
    multi-func: true

  # Error wrapping
  wrapcheck:
    ignoreSigs:
      - .Errorf(
      - errors.New(
      - errors.Unwrap(
      - .Wrap(
      - .Wrapf(
      - .WithMessage(
      - .WithMessagef(
      - .WithStack(
    ignorePackageGlobs:
      - github.com/jmylchreest/tinct/*

# Issues configuration
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Show all issues from all linters
  new: false

  # Exclude specific rules
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude magic number warnings in tests
    - path: _test\.go
      text: "mnd: Magic number"

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA9003:"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Exclude godot issues for TODO comments
    - linters:
        - godot
      source: "^// TODO"

    # Allow blank identifiers in main and init functions
    - path: cmd/
      text: "G104:"
      linters:
        - gosec

    # Allow error shadowing in certain contexts
    - text: 'shadow: declaration of "err"'
      linters:
        - govet

    # Exclude wrapcheck for internal packages
    - path: internal/
      linters:
        - wrapcheck

# Severity settings
severity:
  default-severity: error
  rules:
    - linters:
        - dupl
      severity: info
    - linters:
        - goconst
      severity: warning
