# GoReleaser configuration for Tinct
# https://goreleaser.com/customization/

version: 2

# Project metadata
project_name: tinct

# Before hooks - run before building
before:
  hooks:
    # Ensure dependencies are up to date
    - go mod tidy
    # Prepare plugin dependencies
    - bash scripts/prepare-plugins.sh
    # Generate shell completions
    - bash scripts/generate-completions.sh
    # Run tests before building (linting happens separately in CI)
    - go test ./...

# ============================================================================
# BUILD CONFIGURATION
# ============================================================================
# Build configuration
builds:
  - id: tinct
    main: ./cmd/tinct
    binary: tinct

    # Build for multiple platforms
    goos:
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    ignore:
      - goos: freebsd
        goarch: arm

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - -mod=mod

    ldflags:
      - -s -w
      - -X github.com/jmylchreest/tinct/internal/version.Version={{.Version}}
      - -X github.com/jmylchreest/tinct/internal/version.Commit={{.Commit}}
      - -X github.com/jmylchreest/tinct/internal/version.Date={{.Date}}

    # Ensure we use Go 1.25+
    mod_timestamp: "{{ .CommitTimestamp }}"

  # --------------------------------------------------------------------------
  # INPUT PLUGINS
  # --------------------------------------------------------------------------
  # Plugin: random (Go)
  - id: tinct-plugin-random
    main: .
    binary: tinct-plugin-random
    dir: ./contrib/plugins/input/random

    # Build for multiple platforms
    goos:
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    ignore:
      - goos: freebsd
        goarch: arm

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - -mod=mod

    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

  # --------------------------------------------------------------------------
  # OUTPUT PLUGINS
  # --------------------------------------------------------------------------
  # Plugin: wob (Go)
  - id: tinct-plugin-wob
    main: .
    binary: tinct-plugin-wob
    dir: ./contrib/plugins/output/wob

    # Build for Linux only (wob is a Wayland-specific tool)
    goos:
      - linux

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - -mod=mod

    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

  # Plugin: templater (Go)
  - id: tinct-plugin-templater
    main: .
    binary: tinct-plugin-templater
    dir: ./contrib/plugins/output/templater

    # Build for multiple platforms
    goos:
      - linux
      - freebsd

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    # Ignore specific combinations
    ignore:
      - goos: freebsd
        goarch: arm

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - -mod=mod

    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

  # Plugin: dunstify (Go)
  - id: tinct-plugin-dunstify
    main: .
    binary: tinct-plugin-dunstify
    dir: ./contrib/plugins/output/dunstify

    # Build for Linux only (notifications are Linux-specific)
    goos:
      - linux

    goarch:
      - amd64
      - arm64
      - arm

    goarm:
      - "7"

    # Build flags
    env:
      - CGO_ENABLED=0

    flags:
      - -trimpath
      - -mod=mod

    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

    mod_timestamp: "{{ .CommitTimestamp }}"

# ============================================================================
# ARCHIVES
# ============================================================================
# Archive configuration
archives:
  - id: tinct-archive
    ids:
      - tinct
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

    files:
      - README.md
      - LICENSE
      - docs/**/*

  # Plugin archives - separate downloadable packages
  - id: tinct-plugin-random-archive
    ids:
      - tinct-plugin-random
    name_template: >-
      tinct-plugin-random_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

    files:
      - src: contrib/plugins/input/random/README.md
        dst: README.md
      - src: LICENSE
        dst: LICENSE

  - id: tinct-plugin-wob-archive
    ids:
      - tinct-plugin-wob
    name_template: >-
      tinct-plugin-wob_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    formats: [tar.gz]

    files:
      - src: contrib/plugins/output/wob/README.md
        dst: README.md
      - src: LICENSE
        dst: LICENSE

  - id: tinct-plugin-templater-archive
    ids:
      - tinct-plugin-templater
    name_template: >-
      tinct-plugin-templater_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

    files:
      - src: contrib/plugins/output/templater/README.md
        dst: README.md
      - src: contrib/plugins/output/templater/QUICKSTART.md
        dst: QUICKSTART.md
      - src: contrib/plugins/output/templater/example-config.yaml
        dst: example-config.yaml
      - src: contrib/plugins/output/templater/templates/*.tmpl
        dst: templates/
      - src: LICENSE
        dst: LICENSE

  - id: tinct-plugin-dunstify-archive
    ids:
      - tinct-plugin-dunstify
    name_template: >-
      tinct-plugin-dunstify_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    formats: [tar.gz]

    files:
      - src: LICENSE
        dst: LICENSE

# ============================================================================
# CHECKSUMS & SNAPSHOTS
# ============================================================================
# Checksums
checksum:
  name_template: "checksums.txt"
  algorithm: sha256

# Snapshots (non-tagged builds)
# Format: v0.1.2-abc1234 (next version after tag with git short hash)
snapshot:
  version_template: "{{ incpatch .Version }}-{{ .ShortCommit }}-SNAPSHOT"

# ============================================================================
# CHANGELOG
# ============================================================================
# Changelog generation
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^build\\(deps\\):"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance Improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

# ============================================================================
# PACKAGE MANAGERS
# ============================================================================

# AUR (Arch User Repository) packages
aurs:
  - name: tinct-bin
    ids:
      - tinct-archive
    homepage: "https://github.com/jmylchreest/tinct"
    description: "Generate colour palettes from images and apply system-wide theming"
    maintainers:
      - "John Mylchreest <jmylchreest@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tinct-bin.git"
    url_template: "https://github.com/jmylchreest/tinct/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      # bin
      install -Dm755 "./tinct" "${pkgdir}/usr/bin/tinct"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/tinct/LICENSE"

      # completions
      mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
      mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
      mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
      install -Dm644 "./completions/tinct.bash" "${pkgdir}/usr/share/bash-completion/completions/tinct"
      install -Dm644 "./completions/_tinct" "${pkgdir}/usr/share/zsh/site-functions/_tinct"
      install -Dm644 "./completions/tinct.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/tinct.fish"

      # sbom
      if [ -f "*.sbom.json" ]; then
        install -Dm644 *.sbom.json "${pkgdir}/usr/share/doc/tinct/sbom.json"
      fi

  # Plugin: random
  - name: tinct-plugin-random-bin
    ids:
      - tinct-plugin-random-archive
    homepage: "https://github.com/jmylchreest/tinct"
    description: "Random color palette generator plugin for Tinct"
    maintainers:
      - "John Mylchreest <jmylchreest@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tinct-plugin-random-bin.git"
    depends:
      - tinct-bin
    url_template: "https://github.com/jmylchreest/tinct/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      # bin
      install -Dm755 "./tinct-plugin-random" "${pkgdir}/usr/bin/tinct-plugin-random"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/tinct-plugin-random/LICENSE"

      # sbom
      if [ -f *.sbom.json ]; then
        install -Dm644 *.sbom.json "${pkgdir}/usr/share/doc/tinct-plugin-random/sbom.json"
      fi
    install: |-
      post_install() {
        echo "==> To register the plugin with tinct, run:"
        echo "    tinct plugins add /usr/bin/tinct-plugin-random --no-copy"
      }

      post_upgrade() {
        post_install
      }

  # Plugin: templater
  - name: tinct-plugin-templater-bin
    ids:
      - tinct-plugin-templater-archive
    homepage: "https://github.com/jmylchreest/tinct"
    description: "Template-based output plugin for Tinct"
    maintainers:
      - "John Mylchreest <jmylchreest@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tinct-plugin-templater-bin.git"
    depends:
      - tinct-bin
    url_template: "https://github.com/jmylchreest/tinct/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      # bin
      install -Dm755 "./tinct-plugin-templater" "${pkgdir}/usr/bin/tinct-plugin-templater"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/tinct-plugin-templater/LICENSE"

      # sbom
      if [ -f *.sbom.json ]; then
        install -Dm644 *.sbom.json "${pkgdir}/usr/share/doc/tinct-plugin-templater/sbom.json"
      fi
    install: |-
      post_install() {
        echo "==> To register the plugin with tinct, run:"
        echo "    tinct plugins add /usr/bin/tinct-plugin-templater --no-copy"
      }

      post_upgrade() {
        post_install
      }

  # Plugin: wob
  - name: tinct-plugin-wob-bin
    ids:
      - tinct-plugin-wob-archive
    homepage: "https://github.com/jmylchreest/tinct"
    description: "Wob (Wayland Overlay Bar) output plugin for Tinct"
    maintainers:
      - "John Mylchreest <jmylchreest@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tinct-plugin-wob-bin.git"
    depends:
      - tinct-bin
    url_template: "https://github.com/jmylchreest/tinct/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      # bin
      install -Dm755 "./tinct-plugin-wob" "${pkgdir}/usr/bin/tinct-plugin-wob"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/tinct-plugin-wob/LICENSE"

      # sbom
      if [ -f *.sbom.json ]; then
        install -Dm644 *.sbom.json "${pkgdir}/usr/share/doc/tinct-plugin-wob/sbom.json"
      fi
    install: |-
      post_install() {
        echo "==> To register the plugin with tinct, run:"
        echo "    tinct plugins add /usr/bin/tinct-plugin-wob --no-copy"
      }

      post_upgrade() {
        post_install
      }

  # Plugin: dunstify
  - name: tinct-plugin-dunstify-bin
    ids:
      - tinct-plugin-dunstify-archive
    homepage: "https://github.com/jmylchreest/tinct"
    description: "Desktop notification plugin for Tinct"
    maintainers:
      - "John Mylchreest <jmylchreest@gmail.com>"
    license: MIT
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/tinct-plugin-dunstify-bin.git"
    depends:
      - tinct-bin
    url_template: "https://github.com/jmylchreest/tinct/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      # bin
      install -Dm755 "./tinct-plugin-dunstify" "${pkgdir}/usr/bin/tinct-plugin-dunstify"

      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/tinct-plugin-dunstify/LICENSE"

      # sbom
      if [ -f *.sbom.json ]; then
        install -Dm644 *.sbom.json "${pkgdir}/usr/share/doc/tinct-plugin-dunstify/sbom.json"
      fi
    install: |-
      post_install() {
        echo "==> To register the plugin with tinct, run:"
        echo "    tinct plugins add /usr/bin/tinct-plugin-dunstify --no-copy"
      }

      post_upgrade() {
        post_install
      }
# ============================================================================
# GITHUB RELEASE
# ============================================================================
# GitHub release
release:
  github:
    owner: jmylchreest
    name: tinct

  draft: false
  # Auto-detect prereleases (versions with -SNAPSHOT, -rc, -alpha, -beta, etc.)
  prerelease: auto
  # Don't mark snapshots as latest, but do mark regular releases as latest
  make_latest: "{{ if .IsSnapshot }}false{{ else }}true{{ end }}"
  # Replace assets for snapshots, append for regular releases
  mode: "{{ if .IsSnapshot }}replace{{ else }}append{{ end }}"

  name_template: "{{.ProjectName}} {{.Tag}}"

  header: |
    ## Tinct {{.Version}}

    **Release Date**: {{.Date}}

    ### Installation

    #### Homebrew (macOS/Linux)
    ```bash
    brew install jmylchreest/tap/tinct
    ```

    #### Download Binary
    Download the appropriate binary for your system from the assets below.

  footer: |
    ---

    **Full Changelog**: https://github.com/jmylchreest/tinct/compare/{{.PreviousTag}}...{{.Tag}}

    ## Plugin Installation

    Plugins are available as separate downloadable archives. Install them using:

    ```bash
    # Install compiled Go plugins
    tinct plugins add https://github.com/jmylchreest/tinct/releases/download/{{.Tag}}/tinct-plugin-random_{{.Version}}_Linux_x86_64.tar.gz:random
    tinct plugins add https://github.com/jmylchreest/tinct/releases/download/{{.Tag}}/tinct-plugin-wob_{{.Version}}_Linux_x86_64.tar.gz:wob-tinct
    tinct plugins add https://github.com/jmylchreest/tinct/releases/download/{{.Tag}}/tinct-plugin-templater_{{.Version}}_Linux_x86_64.tar.gz:templater
    tinct plugins add https://github.com/jmylchreest/tinct/releases/download/{{.Tag}}/tinct-plugin-dunstify_{{.Version}}_Linux_x86_64.tar.gz:dunstify
    ```

    Or download manually from the assets below and add locally:
    ```bash
    tinct plugins add ./random
    tinct plugins add ./wob-tinct
    tinct plugins add ./templater
    tinct plugins add ./dunstify
    ```

    ## What's Next?

    -  [Documentation](https://github.com/jmylchreest/tinct/blob/main/README.md)
    -  [Plugin Development Guide](https://github.com/jmylchreest/tinct/blob/main/contrib/README.md)
    -  [Report Issues](https://github.com/jmylchreest/tinct/issues)
    -  [Discussions](https://github.com/jmylchreest/tinct/discussions)

# ============================================================================
# ANNOUNCEMENTS
# ============================================================================
# Announce release
announce:
  skip: "{{gt .Patch 0}}"

  discord:
    enabled: true
    message_template: |
      **Tinct {{.Tag}}** has been released!

      {{.ReleaseNotes}}

      Download: {{.ReleaseURL}}

# ============================================================================
# SBOMS
# ============================================================================
# SBOMs (Software Bill of Materials)
sboms:
  - id: archive
    artifacts: archive
  - id: source
    artifacts: source
