package hyprpaper

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestHyprpaperPlugin runs all standard plugin tests using shared utilities.
func TestHyprpaperPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:         "hyprpaper",
		ExpectedFiles:        []string{"tinct-hyprpaper.conf"},
		ExpectedBinaryName:   "hyprpaper",
		ExpectedDirSubstring: "hypr", // Plugin uses .config/hypr, not .config/hyprpaper
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestHyprpaperPlugin_ContentValidation tests hyprpaper-specific content requirements.
func TestHyprpaperPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-hyprpaper.conf"])

	// Check for required configuration directives (common to all versions).
	requiredStrings := []string{
		"# Hyprpaper configuration generated by Tinct",
		"wallpaper",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}

	// Check for version-specific content (either old or new format).
	// Old format (pre-0.8.0): uses "preload" and "wallpaper ="
	// New format (0.8.0+): uses "wallpaper {" block syntax
	hasOldFormat := strings.Contains(content, "preload")
	hasNewFormat := strings.Contains(content, "wallpaper {")

	if !hasOldFormat && !hasNewFormat {
		t.Errorf("Generated content missing version-specific wallpaper config (neither old 'preload' nor new 'wallpaper {' block found)")
	}
}
