package hyprpaper

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestHyprpaperPlugin runs all standard plugin tests using shared utilities.
func TestHyprpaperPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:         "hyprpaper",
		ExpectedFiles:        []string{"tinct-hyprpaper.conf"},
		ExpectedBinaryName:   "hyprpaper",
		ExpectedDirSubstring: "hypr", // Plugin uses .config/hypr, not .config/hyprpaper
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestHyprpaperPlugin_ContentValidation tests hyprpaper-specific content requirements.
func TestHyprpaperPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-hyprpaper.conf"])

	// Check for required configuration directives.
	requiredStrings := []string{
		"# Hyprpaper configuration generated by Tinct",
		"preload",
		"wallpaper",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}
}
