package swayosd

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestSwayOSDPlugin runs all standard plugin tests using shared utilities.
func TestSwayOSDPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "swayosd",
		ExpectedFiles:      []string{"style.css"},
		ExpectedBinaryName: "swayosd-client",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestSwayOSDPlugin_ContentValidation tests swayosd-specific content requirements.
func TestSwayOSDPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["style.css"])

	// Check for required CSS content
	requiredStrings := []string{
		"/* SwayOSD colour theme generated by Tinct",
		"window#osd",
		"background:",
		"color:",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: dark") {
		t.Error("Generated content missing theme type")
	}
}

// TestSwayOSDPlugin_GenerateWithLightTheme tests light theme generation.
func TestSwayOSDPlugin_GenerateWithLightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["style.css"])

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: light") {
		t.Error("Generated content missing light theme type")
	}
}

// TestSwayOSDPlugin_CustomOutputDir tests custom output directory handling.
func TestSwayOSDPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestSwayOSDPlugin_GetEmbeddedTemplates tests embedded template access.
func TestSwayOSDPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	found := false
	for _, entry := range entries {
		if entry.Name() == "style.css.tmpl" {
			found = true
			break
		}
	}

	if !found {
		t.Error("Template file style.css.tmpl not found in embedded filesystem")
	}
}

// TestSwayOSDPlugin_PrepareThemeData tests theme data preparation.
func TestSwayOSDPlugin_PrepareThemeData(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	data := plugin.prepareThemeData(palette)

	// Check that PaletteHelper is created properly
	if data == nil {
		t.Fatal("prepareThemeData should return non-nil PaletteHelper")
	}

	// Check that required roles exist
	requiredRoles := []colour.ColourRole{
		colour.RoleBackground,
		colour.RoleForeground,
	}

	for _, role := range requiredRoles {
		if !data.Has(role) {
			t.Errorf("PaletteHelper missing required role: %s", role)
		}
	}

	// Check that theme type matches
	if data.ThemeTypeString() != "dark" {
		t.Errorf("ThemeTypeString() = %s, want dark", data.ThemeTypeString())
	}
}
