package waybar

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestWaybarPlugin runs all standard plugin tests using shared utilities.
func TestWaybarPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "waybar",
		ExpectedFiles:      []string{"tinct.css", "tinct-colours.css"},
		ExpectedBinaryName: "waybar",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestWaybarPlugin_ContentValidation tests waybar-specific content requirements.
func TestWaybarPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	// Check main CSS file
	mainCSS := string(files["tinct.css"])
	requiredMainStrings := []string{
		"Waybar",
		"@import",
		"tinct-colours.css",
	}

	for _, required := range requiredMainStrings {
		if !strings.Contains(mainCSS, required) {
			t.Errorf("Main CSS missing required string: %s", required)
		}
	}

	// Check colours CSS file
	coloursCSS := string(files["tinct-colours.css"])
	requiredColourStrings := []string{
		"/* Waybar colour variables generated by Tinct",
		"@define-color background",
		"@define-color foreground",
		"@define-color accent1",
	}

	for _, required := range requiredColourStrings {
		if !strings.Contains(coloursCSS, required) {
			t.Errorf("Colours CSS missing required string: %s", required)
		}
	}

	// Check that theme type is present
	if !strings.Contains(coloursCSS, "Detected theme: dark") {
		t.Error("Generated content missing theme type")
	}
}

// TestWaybarPlugin_GenerateWithLightTheme tests light theme generation.
func TestWaybarPlugin_GenerateWithLightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	coloursCSS := string(files["tinct-colours.css"])

	// Check that theme type is present
	if !strings.Contains(coloursCSS, "Detected theme: light") {
		t.Error("Generated content missing light theme type")
	}
}

// TestWaybarPlugin_CustomOutputDir tests custom output directory handling.
func TestWaybarPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestWaybarPlugin_GetEmbeddedTemplates tests embedded template access.
func TestWaybarPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	expectedFiles := []string{"tinct.css.tmpl", "tinct-colours.css.tmpl"}
	for _, expected := range expectedFiles {
		found := false
		for _, entry := range entries {
			if entry.Name() == expected {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("Template file %s not found in embedded filesystem", expected)
		}
	}
}

// TestWaybarPlugin_AllColorsExported tests that all colors are exported as CSS variables.
func TestWaybarPlugin_AllColorsExported(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	coloursCSS := string(files["tinct-colours.css"])

	// Check that core colors are present (using GTK @define-color format)
	coreColors := []string{
		"@define-color background",
		"@define-color foreground",
		"@define-color accent1",
		"@define-color danger",
		"@define-color warning",
		"@define-color success",
		"@define-color info",
	}

	for _, color := range coreColors {
		if !strings.Contains(coloursCSS, color) {
			t.Errorf("Colours CSS missing color variable: %s", color)
		}
	}
}
