package alacritty

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestAlacrittyPlugin runs all standard plugin tests using shared utilities.
func TestAlacrittyPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "alacritty",
		ExpectedFiles:      []string{"tinct-colors.toml"},
		ExpectedBinaryName: "alacritty",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestAlacrittyPlugin_ContentValidation tests alacritty-specific content requirements.
func TestAlacrittyPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-colors.toml"])

	// Check for required TOML sections.
	requiredStrings := []string{
		"# Alacritty colour theme generated by Tinct",
		"[colors.primary]",
		"foreground",
		"background",
		"[colors.normal]",
		"black",
		"red",
		"green",
		"yellow",
		"blue",
		"magenta",
		"cyan",
		"white",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}
}
