// Package cli provides the command-line interface for Tinct.
package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/jmylchreest/tinct/internal/manifest"
)

const unknownValue = "unknown"

var (
	// Files command flags.
	filesPlugin  string
	filesVerbose bool
	filesForce   bool
	filesCache   bool
)

// filesCmd represents the files command.
var filesCmd = &cobra.Command{
	Use:   "files",
	Short: "Manage tinct-generated files",
	Long: `Manage files that have been generated by tinct.

This command allows you to list, verify, delete, and clean up files that
tinct has created. All tracked files are recorded in a manifest at
~/.local/share/tinct/manifest.json.

Commands:
  list     - List all tracked files
  delete   - Delete specific files or all files from a plugin
  adopt    - Adopt existing files into the manifest for a plugin
  verify   - Verify file integrity against manifest checksums
  orphans  - List files from plugins that are no longer available
  clean    - Remove orphaned files from disk`,
	RunE: runFilesList, // Default to list
}

// filesListCmd represents the files list command.
var filesListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all tracked files",
	Long: `List all files that have been generated by tinct.

Shows file path, plugin name, size, and last update time.
Use --plugin to filter by a specific plugin.`,
	RunE: runFilesList,
}

// filesDeleteCmd represents the files delete command.
var filesDeleteCmd = &cobra.Command{
	Use:   "delete [files...]",
	Short: "Delete tracked files",
	Long: `Delete files that were generated by tinct.

Specify file paths to delete specific files, or use --plugin to delete
all files from a specific plugin. Use --force to skip confirmation.

Examples:
  tinct files delete ~/.config/hypr/colors.conf
  tinct files delete --plugin kde-plasma
  tinct files delete --plugin kde-plasma --force`,
	RunE: runFilesDelete,
}

// filesAdoptCmd represents the files adopt command.
var filesAdoptCmd = &cobra.Command{
	Use:   "adopt <plugin> <files...>",
	Short: "Adopt existing files into the manifest",
	Long: `Adopt existing files into the manifest for tracking by a specific plugin.

This is useful when you have existing configuration files that you want
tinct to manage. The files will be tracked and associated with the
specified plugin.

You must specify both the plugin name and the file(s) to adopt.

Examples:
  tinct files adopt hyprland ~/.config/hypr/colors.conf
  tinct files adopt kde-plasma ~/.local/share/color-schemes/*.colors
  tinct files adopt waybar ~/.config/waybar/tinct.css`,
	Args: cobra.MinimumNArgs(2),
	RunE: runFilesAdopt,
}

// filesVerifyCmd represents the files verify command.
var filesVerifyCmd = &cobra.Command{
	Use:   "verify",
	Short: "Verify file integrity",
	Long: `Verify that tracked files match their recorded checksums.

This helps detect if files have been modified outside of tinct.
Use --plugin to verify only files from a specific plugin.`,
	RunE: runFilesVerify,
}

// filesOrphansCmd represents the files orphans command.
var filesOrphansCmd = &cobra.Command{
	Use:   "orphans",
	Short: "List orphaned files",
	Long: `List files that were created by plugins that are no longer available.

These files were generated by plugins that have since been removed or
disabled. Use 'tinct files clean' to remove them.`,
	RunE: runFilesOrphans,
}

// filesCleanCmd represents the files clean command.
var filesCleanCmd = &cobra.Command{
	Use:   "clean",
	Short: "Remove orphaned files",
	Long: `Remove files that were created by plugins that are no longer available.

This deletes orphaned files from disk and removes them from the manifest.
Use --force to skip confirmation.`,
	RunE: runFilesClean,
}

func init() {
	// Add subcommands to files command.
	filesCmd.AddCommand(filesListCmd)
	filesCmd.AddCommand(filesDeleteCmd)
	filesCmd.AddCommand(filesAdoptCmd)
	filesCmd.AddCommand(filesVerifyCmd)
	filesCmd.AddCommand(filesOrphansCmd)
	filesCmd.AddCommand(filesCleanCmd)

	// Common flags.
	filesCmd.PersistentFlags().StringVar(&filesPlugin, "plugin", "", "Filter by plugin name")
	filesCmd.PersistentFlags().BoolVarP(&filesVerbose, "verbose", "v", false, "Verbose output")
	filesCmd.PersistentFlags().BoolVar(&filesCache, "cache", false, "Show/manage cached files (e.g., google-genai images)")

	// Delete/clean specific flags.
	filesDeleteCmd.Flags().BoolVar(&filesForce, "force", false, "Skip confirmation")
	filesCleanCmd.Flags().BoolVar(&filesForce, "force", false, "Skip confirmation")
}

// runFilesList lists all tracked files.
func runFilesList(_ *cobra.Command, _ []string) error {
	// Handle cache listing separately.
	if filesCache {
		return runCacheList()
	}

	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	var files map[string]*manifest.FileEntry
	if filesPlugin != "" {
		files = mgr.GetFilesByPlugin(filesPlugin)
	} else {
		files = mgr.GetAllFiles()
	}

	if len(files) == 0 {
		if filesPlugin != "" {
			fmt.Printf("No files tracked for plugin: %s\n", filesPlugin)
		} else {
			fmt.Println("No files tracked by tinct")
		}
		return nil
	}

	// Sort files by path for consistent output.
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	// Create table for output.
	table := NewTable([]string{"File", "Plugin", "Size", "Updated"})

	for _, path := range paths {
		entry := files[path]
		// Shorten home directory path for display.
		displayPath := shortenPath(path)
		size := formatSize(entry.Size)
		updated := entry.UpdatedAt.Format("2006-01-02 15:04")

		table.AddRow([]string{displayPath, entry.Plugin, size, updated})
	}

	fmt.Println(table.Render())
	fmt.Printf("\nTotal: %d files, %s\n", len(files), formatSize(mgr.TotalSize()))

	return nil
}

// runCacheList lists cached files (e.g., google-genai generated images).
func runCacheList() error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	cacheDir := filepath.Join(home, ".cache", "tinct")

	// Check if cache directory exists.
	if _, err := os.Stat(cacheDir); os.IsNotExist(err) {
		fmt.Println("No cached files found")
		return nil
	}

	// Walk the cache directory.
	var cacheFiles []struct {
		path    string
		size    int64
		modTime string
		plugin  string
	}

	var totalSize int64

	err = filepath.Walk(cacheDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // Skip files we can't access
		}
		if info.IsDir() {
			return nil
		}

		// Skip metadata JSON files in listing (they're shown with their images)
		if strings.HasSuffix(path, ".json") {
			return nil
		}

		// Determine plugin from path.
		relPath, err := filepath.Rel(cacheDir, path)
		if err != nil {
			relPath = path // Fallback to full path
		}
		parts := strings.SplitN(relPath, string(filepath.Separator), 2)
		plugin := unknownValue
		if len(parts) > 0 {
			plugin = parts[0]
		}

		cacheFiles = append(cacheFiles, struct {
			path    string
			size    int64
			modTime string
			plugin  string
		}{
			path:    path,
			size:    info.Size(),
			modTime: info.ModTime().Format("2006-01-02 15:04"),
			plugin:  plugin,
		})
		totalSize += info.Size()

		return nil
	})

	if err != nil {
		return fmt.Errorf("failed to walk cache directory: %w", err)
	}

	if len(cacheFiles) == 0 {
		fmt.Println("No cached files found")
		return nil
	}

	// Create table for output.
	table := NewTable([]string{"File", "Plugin", "Size", "Modified"})

	for _, f := range cacheFiles {
		displayPath := shortenPath(f.path)
		size := formatSize(f.size)
		table.AddRow([]string{displayPath, f.plugin, size, f.modTime})
	}

	fmt.Println(table.Render())
	fmt.Printf("\nTotal: %d cached files, %s\n", len(cacheFiles), formatSize(totalSize))

	return nil
}

// runFilesDelete deletes tracked files.
func runFilesDelete(_ *cobra.Command, args []string) error { //nolint:gocyclo // multiple deletion modes with error handling
	// Handle cache deletion separately.
	if filesCache {
		return runCacheDelete(args)
	}

	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	var filesToDelete []string

	switch {
	case len(args) > 0:
		// Delete specific files.
		for _, arg := range args {
			absPath, err := filepath.Abs(arg)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: invalid path %s: %v\n", arg, err)
				continue
			}
			if mgr.IsTracked(absPath) {
				filesToDelete = append(filesToDelete, absPath)
			} else {
				fmt.Fprintf(os.Stderr, "Warning: %s is not tracked by tinct\n", arg)
			}
		}
	case filesPlugin != "":
		// Delete all files from a plugin.
		files := mgr.GetFilesByPlugin(filesPlugin)
		for path := range files {
			filesToDelete = append(filesToDelete, path)
		}
	default:
		return fmt.Errorf("specify files to delete or use --plugin")
	}

	if len(filesToDelete) == 0 {
		fmt.Println("No files to delete")
		return nil
	}

	// Confirm deletion.
	if !filesForce {
		fmt.Printf("Will delete %d file(s):\n", len(filesToDelete))
		for _, path := range filesToDelete {
			fmt.Printf("  %s\n", shortenPath(path))
		}
		fmt.Print("\nConfirm deletion? [y/N] ")
		var response string
		if _, err := fmt.Scanln(&response); err != nil || !strings.EqualFold(response, "y") {
			fmt.Println("Cancelled")
			return nil
		}
	}

	// Delete files.
	deleted := 0
	for _, path := range filesToDelete {
		if err := mgr.DeleteFile(path); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete %s: %v\n", shortenPath(path), err)
		} else {
			if filesVerbose {
				fmt.Printf("Deleted: %s\n", shortenPath(path))
			}
			deleted++
		}
	}

	// Save manifest.
	if err := mgr.Save(); err != nil {
		return fmt.Errorf("failed to save manifest: %w", err)
	}

	fmt.Printf("Deleted %d file(s)\n", deleted)
	return nil
}

// runCacheDelete deletes cached files.
func runCacheDelete(args []string) error { //nolint:gocyclo,gocognit // multiple cache types with selective deletion
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get home directory: %w", err)
	}

	cacheDir := filepath.Join(home, ".cache", "tinct")

	var filesToDelete []string

	switch {
	case len(args) > 0:
		for _, arg := range args {
			absPath, err := filepath.Abs(arg)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: invalid path %s: %v\n", arg, err)
				continue
			}
			if _, err := os.Stat(absPath); err == nil {
				if strings.HasPrefix(absPath, cacheDir) {
					filesToDelete = append(filesToDelete, absPath)
					// Also delete associated metadata JSON if it exists.
					metadataPath := strings.TrimSuffix(absPath, filepath.Ext(absPath)) + ".json"
					if _, err := os.Stat(metadataPath); err == nil {
						filesToDelete = append(filesToDelete, metadataPath)
					}
				} else {
					fmt.Fprintf(os.Stderr, "Warning: %s is not in cache directory\n", arg)
				}
			} else {
				fmt.Fprintf(os.Stderr, "Warning: %s does not exist\n", arg)
			}
		}
	case filesPlugin != "":
		pluginCacheDir := filepath.Join(cacheDir, filesPlugin)
		if _, err := os.Stat(pluginCacheDir); os.IsNotExist(err) {
			fmt.Printf("No cached files for plugin: %s\n", filesPlugin)
			return nil
		}

		err := filepath.Walk(pluginCacheDir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}
			if !info.IsDir() {
				filesToDelete = append(filesToDelete, path)
			}
			return nil
		})
		if err != nil {
			return fmt.Errorf("failed to walk cache directory: %w", err)
		}
	default:
		if _, err := os.Stat(cacheDir); os.IsNotExist(err) {
			fmt.Println("No cached files found")
			return nil
		}

		err := filepath.Walk(cacheDir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return nil
			}
			if !info.IsDir() {
				filesToDelete = append(filesToDelete, path)
			}
			return nil
		})
		if err != nil {
			return fmt.Errorf("failed to walk cache directory: %w", err)
		}
	}

	if len(filesToDelete) == 0 {
		fmt.Println("No cached files to delete")
		return nil
	}

	// Confirm deletion.
	if !filesForce {
		fmt.Printf("Will delete %d cached file(s):\n", len(filesToDelete))
		for _, path := range filesToDelete {
			fmt.Printf("  %s\n", shortenPath(path))
		}
		fmt.Print("\nConfirm deletion? [y/N] ")
		var response string
		if _, err := fmt.Scanln(&response); err != nil || !strings.EqualFold(response, "y") {
			fmt.Println("Cancelled")
			return nil
		}
	}

	// Delete files.
	deleted := 0
	for _, path := range filesToDelete {
		if err := os.Remove(path); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete %s: %v\n", shortenPath(path), err)
		} else {
			if filesVerbose {
				fmt.Printf("Deleted: %s\n", shortenPath(path))
			}
			deleted++
		}
	}

	fmt.Printf("Deleted %d cached file(s)\n", deleted)
	return nil
}

// runFilesAdopt adopts existing files into the manifest for a specific plugin.
func runFilesAdopt(_ *cobra.Command, args []string) error { //nolint:gocyclo,gocognit // file discovery and manifest update
	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	pluginName := args[0]
	filePaths := args[1:]

	// Verify plugin exists.
	if _, ok := sharedPluginManager.GetOutputPlugin(pluginName); !ok {
		return fmt.Errorf("unknown plugin: %s", pluginName)
	}

	adopted := 0

	for _, pattern := range filePaths {
		// Expand glob patterns.
		matches, err := filepath.Glob(pattern)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Invalid pattern %s: %v\n", pattern, err)
			continue
		}

		if len(matches) == 0 {
			// Try as literal path.
			matches = []string{pattern}
		}

		for _, path := range matches {
			absPath, err := filepath.Abs(path)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: invalid path %s: %v\n", path, err)
				continue
			}

			// Check if file exists.
			content, err := os.ReadFile(absPath) // #nosec G304 -- Path from manifest, validated above
			if err != nil {
				fmt.Fprintf(os.Stderr, "Warning: cannot read %s: %v\n", path, err)
				continue
			}

			// Check if already tracked.
			if mgr.IsTracked(absPath) {
				if filesVerbose {
					fmt.Printf("Already tracked: %s\n", shortenPath(absPath))
				}
				continue
			}

			// Record in manifest.
			if err := mgr.RecordFile(pluginName, absPath, content); err != nil {
				fmt.Fprintf(os.Stderr, "Failed to record %s: %v\n", path, err)
				continue
			}

			if filesVerbose {
				fmt.Printf("Adopted: %s\n", shortenPath(absPath))
			}
			adopted++
		}
	}

	// Save manifest.
	if err := mgr.Save(); err != nil {
		return fmt.Errorf("failed to save manifest: %w", err)
	}

	if adopted == 0 {
		fmt.Println("No new files to adopt")
	} else {
		fmt.Printf("Adopted %d file(s) for plugin %s\n", adopted, pluginName)
	}
	return nil
}

// runFilesVerify verifies file integrity.
func runFilesVerify(_ *cobra.Command, _ []string) error {
	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	var files map[string]*manifest.FileEntry
	if filesPlugin != "" {
		files = mgr.GetFilesByPlugin(filesPlugin)
	} else {
		files = mgr.GetAllFiles()
	}

	if len(files) == 0 {
		fmt.Println("No files to verify")
		return nil
	}

	// Sort files by path.
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	verified := 0
	modified := 0
	missing := 0

	for _, path := range paths {
		exists, matches, err := mgr.VerifyFile(path)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error verifying %s: %v\n", shortenPath(path), err)
			continue
		}

		switch {
		case !exists:
			if filesVerbose {
				fmt.Printf("MISSING: %s\n", shortenPath(path))
			}
			missing++
		case !matches:
			fmt.Printf("MODIFIED: %s\n", shortenPath(path))
			modified++
		default:
			if filesVerbose {
				fmt.Printf("OK: %s\n", shortenPath(path))
			}
			verified++
		}
	}

	fmt.Printf("\nVerified: %d, Modified: %d, Missing: %d\n", verified, modified, missing)

	if modified > 0 || missing > 0 {
		return fmt.Errorf("verification failed")
	}
	return nil
}

// runFilesOrphans lists orphaned files.
func runFilesOrphans(_ *cobra.Command, _ []string) error {
	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	// Get list of available plugins.
	availablePlugins := getAvailablePluginNames()

	orphans := mgr.GetOrphans(availablePlugins)

	if len(orphans) == 0 {
		fmt.Println("No orphaned files")
		return nil
	}

	// Group by plugin.
	byPlugin := make(map[string][]string)
	for path, entry := range orphans {
		byPlugin[entry.Plugin] = append(byPlugin[entry.Plugin], path)
	}

	// Sort plugins.
	plugins := make([]string, 0, len(byPlugin))
	for plugin := range byPlugin {
		plugins = append(plugins, plugin)
	}
	sort.Strings(plugins)

	for _, plugin := range plugins {
		paths := byPlugin[plugin]
		sort.Strings(paths)
		fmt.Printf("\nPlugin: %s (not available)\n", plugin)
		for _, path := range paths {
			fmt.Printf("  %s\n", shortenPath(path))
		}
	}

	fmt.Printf("\nTotal: %d orphaned file(s)\n", len(orphans))
	fmt.Println("Use 'tinct files clean' to remove these files")

	return nil
}

// runFilesClean removes orphaned files.
func runFilesClean(_ *cobra.Command, _ []string) error {
	mgr, err := manifest.NewManager("")
	if err != nil {
		return fmt.Errorf("failed to create manifest manager: %w", err)
	}
	if err := mgr.Load(); err != nil {
		return fmt.Errorf("failed to load manifest: %w", err)
	}

	// Get list of available plugins.
	availablePlugins := getAvailablePluginNames()

	orphans := mgr.GetOrphans(availablePlugins)

	if len(orphans) == 0 {
		fmt.Println("No orphaned files to clean")
		return nil
	}

	// Confirm deletion.
	if !filesForce {
		fmt.Printf("Will delete %d orphaned file(s):\n", len(orphans))
		for path := range orphans {
			fmt.Printf("  %s\n", shortenPath(path))
		}
		fmt.Print("\nConfirm deletion? [y/N] ")
		var response string
		if _, err := fmt.Scanln(&response); err != nil || !strings.EqualFold(response, "y") {
			fmt.Println("Cancelled")
			return nil
		}
	}

	// Delete files.
	deleted := 0
	for path := range orphans {
		if err := mgr.DeleteFile(path); err != nil {
			fmt.Fprintf(os.Stderr, "Failed to delete %s: %v\n", shortenPath(path), err)
		} else {
			if filesVerbose {
				fmt.Printf("Deleted: %s\n", shortenPath(path))
			}
			deleted++
		}
	}

	// Save manifest.
	if err := mgr.Save(); err != nil {
		return fmt.Errorf("failed to save manifest: %w", err)
	}

	fmt.Printf("Deleted %d orphaned file(s)\n", deleted)
	return nil
}

// getAvailablePluginNames returns the names of all available plugins.
// This includes both built-in and external plugins loaded from the manifest.
func getAvailablePluginNames() []string {
	// Load plugin lock to get external plugins.
	// Errors are ignored as we fall back to built-in plugins only.
	lock, _, err := loadPluginManifest()
	if err != nil {
		lock = nil
	}
	mgr := createManagerFromManifest(lock)

	inputPlugins := mgr.AllInputPlugins()
	outputPlugins := mgr.AllOutputPlugins()
	names := make([]string, 0, len(inputPlugins)+len(outputPlugins))

	for name := range inputPlugins {
		names = append(names, name)
	}

	for name := range outputPlugins {
		names = append(names, name)
	}

	return names
}

// shortenPath shortens a path by replacing home directory with ~.
func shortenPath(path string) string {
	home, err := os.UserHomeDir()
	if err != nil {
		return path
	}
	if strings.HasPrefix(path, home) {
		return "~" + path[len(home):]
	}
	return path
}

// formatSize formats a byte count as a human-readable string.
func formatSize(bytes int64) string {
	const unit = 1024
	if bytes < unit {
		return fmt.Sprintf("%d B", bytes)
	}
	div, exp := int64(unit), 0
	for n := bytes / unit; n >= unit; n /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(bytes)/float64(div), "KMGTPE"[exp])
}
