package main

import (
	"bytes"
	"context"
	"embed"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/jmylchreest/tinct/pkg/colour"
	tinctplugin "github.com/jmylchreest/tinct/pkg/plugin"
	"github.com/jmylchreest/tinct/pkg/plugin/config"
	"github.com/jmylchreest/tinct/pkg/plugin/paths"
	tincttemplate "github.com/jmylchreest/tinct/pkg/template"
	"github.com/jmylchreest/tinct/pkg/util/appdetect"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

const (
	// ptyxisAppID matches APP_ID in Ptyxis's meson build — the GNOME-style
	// reverse-DNS application id used as the user-data subdirectory name.
	// Ref: ptyxis_get_user_palettes_dir() in src/ptyxis-palette.c.
	ptyxisAppID = "org.gnome.Ptyxis"

	// ptyxisFlatpakID is the Flathub application id for Ptyxis. Inside the
	// sandbox XDG_DATA_HOME maps to ~/.var/app/<flatpak-id>/data, so the
	// host-visible palette dir is ~/.var/app/<flatpak-id>/data/<app-id>/palettes.
	ptyxisFlatpakID = "app.devsuite.Ptyxis"

	// paletteFilename is the filename written to the Ptyxis palette dir. The
	// basename (minus .palette) becomes the palette id Ptyxis exposes.
	paletteFilename = "tinct.palette"
)

// Plugin implements the tinct OutputPlugin interface for Ptyxis terminal palettes.
type Plugin struct {
	version   string
	commit    string
	date      string
	outputDir string
}

// nativeDataDir returns Ptyxis's user data dir for a native install:
// $XDG_DATA_HOME/org.gnome.Ptyxis (default ~/.local/share/org.gnome.Ptyxis).
func nativeDataDir() string {
	return filepath.Join(paths.XDGDataDir(), ptyxisAppID)
}

// flatpakDataDir returns Ptyxis's user data dir as visible from the host
// when Ptyxis is installed via Flatpak.
func flatpakDataDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("failed to get home directory: %w", err)
	}
	return filepath.Join(home, ".var", "app", ptyxisFlatpakID, "data", ptyxisAppID), nil
}

// detectPalettesDir picks the right palettes dir for the user's install:
// Flatpak host-visible path if Ptyxis is only installed via Flatpak,
// otherwise the native XDG_DATA_HOME path. Returns the directory plus a
// best-effort install type ("native" / "flatpak" / "") used by PreExecute.
func detectPalettesDir() (palettesDir, installType string, err error) {
	flatpakData, ferr := flatpakDataDir()
	if ferr != nil {
		return "", "", ferr
	}

	switch appdetect.GetInstallationType([]string{"ptyxis"}, []string{nativeDataDir(), flatpakData}) {
	case "flatpak":
		return filepath.Join(flatpakData, "palettes"), "flatpak", nil
	case "native", "directory":
		return filepath.Join(nativeDataDir(), "palettes"), "native", nil
	}
	return "", "", nil
}

// resolveOutputDir returns the effective output directory.
//
// Resolution order: --output-dir flag → TINCT_PLUGIN_PTYXIS_OUTPUT_DIR
// env var → auto-detected install path → native fallback.
func (p *Plugin) resolveOutputDir() (string, error) {
	if p.outputDir != "" {
		return p.outputDir, nil
	}
	if env := os.Getenv(config.EnvName("ptyxis", "output_dir")); env != "" {
		return env, nil
	}
	dir, _, err := detectPalettesDir()
	if err != nil {
		return "", err
	}
	if dir != "" {
		return dir, nil
	}
	return filepath.Join(nativeDataDir(), "palettes"), nil
}

// Generate creates a Ptyxis palette file from the protocol palette data.
//
// Single-mode (no AlternateTheme): writes Foreground/Background/Cursor +
// Color0..15 directly under [Palette]. Ptyxis derives whether the palette
// is light or dark from the background luminance (is_dark() in
// ptyxis-palette.c).
//
// Dual-mode (AlternateTheme present): emits a [Palette] header plus
// [Light] and [Dark] sections holding the variants. Ptyxis switches
// between them based on the system colour preference.
func (p *Plugin) Generate(_ context.Context, palette tinctplugin.PaletteData) (map[string][]byte, error) {
	tmpl, err := p.loadTemplate(palette.Verbose)
	if err != nil {
		return nil, err
	}

	primaryThemeData := convertPaletteDataToThemeData(palette)
	primaryFace, err := executeFace(tmpl, primaryThemeData)
	if err != nil {
		return nil, fmt.Errorf("failed to render primary face: %w", err)
	}

	var paletteBuf bytes.Buffer
	paletteBuf.WriteString("# Ptyxis colour palette generated by Tinct\n")
	paletteBuf.WriteString("[Palette]\n")
	paletteBuf.WriteString("Name=Tinct\n")

	if palette.AlternateTheme != nil {
		if palette.Verbose {
			fmt.Fprintf(os.Stderr, "   Generating dual-theme (light + dark)\n")
		}

		alternatePaletteData := tinctplugin.PaletteData{
			Colours:    palette.AlternateTheme.Colours,
			AllColours: palette.AlternateTheme.AllColours,
			ThemeType:  palette.AlternateTheme.ThemeType,
			Verbose:    palette.Verbose,
		}
		alternateThemeData := convertPaletteDataToThemeData(alternatePaletteData)
		alternateFace, err := executeFace(tmpl, alternateThemeData)
		if err != nil {
			return nil, fmt.Errorf("failed to render alternate face: %w", err)
		}

		light, dark := splitByMode(primaryThemeData, alternateThemeData, primaryFace, alternateFace)
		paletteBuf.WriteString("\n[Light]\n")
		paletteBuf.Write(light)
		paletteBuf.WriteString("\n[Dark]\n")
		paletteBuf.Write(dark)
	} else {
		paletteBuf.Write(primaryFace)
	}

	return p.writePaletteFile(paletteBuf.Bytes())
}

// loadTemplate loads and parses the Ptyxis palette template.
func (p *Plugin) loadTemplate(verbose bool) (*template.Template, error) {
	loader := tincttemplate.New("ptyxis", templatesFS)
	if verbose {
		loader.WithVerbose(true, &stdLogger{})
	}

	tmplContent, fromCustom, err := loader.Load("templates/tinct.palette.tmpl")
	if err != nil {
		return nil, fmt.Errorf("failed to load template: %w", err)
	}
	if verbose {
		if fromCustom {
			fmt.Fprintf(os.Stderr, "   Template source: custom (%s)\n", loader.CustomPath("templates/tinct.palette.tmpl"))
		} else {
			fmt.Fprintf(os.Stderr, "   Template source: embedded\n")
		}
	}

	tmpl, err := template.New("palette").
		Funcs(tincttemplate.TemplateFuncs()).
		Parse(string(tmplContent))
	if err != nil {
		return nil, fmt.Errorf("failed to parse template: %w", err)
	}
	return tmpl, nil
}

// executeFace renders the face body (the colour keys for one variant) by
// running the template against themeData. The output has no
// [Palette]/[Light]/[Dark] header; the caller assembles those sections.
func executeFace(tmpl *template.Template, themeData *colour.ThemeData) ([]byte, error) {
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, themeData); err != nil {
		return nil, fmt.Errorf("template execute: %w", err)
	}
	return buf.Bytes(), nil
}

// splitByMode returns (lightFace, darkFace) given the two themes and their
// rendered faces. If both themes report the same mode (shouldn't happen
// via the dual-theme pipeline), `a` is treated as light.
func splitByMode(a, b *colour.ThemeData, faceA, faceB []byte) (light, dark []byte) {
	if a.ThemeType() == colour.ThemeLight {
		return faceA, faceB
	}
	return faceB, faceA
}

// writePaletteFile writes the palette content to the resolved output dir
// (creating the dir if needed) and returns the file map for tinct.
func (p *Plugin) writePaletteFile(content []byte) (map[string][]byte, error) {
	outputDir, err := p.resolveOutputDir()
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(outputDir, 0o750); err != nil {
		return nil, fmt.Errorf("failed to create palette directory %q: %w", outputDir, err)
	}
	return map[string][]byte{filepath.Join(outputDir, paletteFilename): content}, nil
}

// PreExecute checks if Ptyxis is installed (binary on PATH or palette dir
// exists either natively or under the Flatpak host-visible path).
func (p *Plugin) PreExecute(_ context.Context) (skip bool, reason string, err error) {
	flatpakData, ferr := flatpakDataDir()
	if ferr != nil {
		return true, "cannot determine home directory", nil
	}
	if !appdetect.IsPresentAny([]string{"ptyxis"}, []string{nativeDataDir(), flatpakData}) {
		return true, "Ptyxis terminal is not installed", nil
	}
	return false, "", nil
}

// PostExecute prints installation guidance after writing the palette.
// Because the file is written directly into Ptyxis's watched palette dir,
// PtyxisUserPalettes picks it up live via GFileMonitor — no import step.
func (p *Plugin) PostExecute(_ context.Context, files []string) error {
	if len(files) == 0 {
		return nil
	}
	fmt.Fprintf(os.Stderr, "\n")
	fmt.Fprintf(os.Stderr, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")
	fmt.Fprintf(os.Stderr, "  Ptyxis Palette Installation\n")
	fmt.Fprintf(os.Stderr, "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n")
	fmt.Fprintf(os.Stderr, "\n")
	fmt.Fprintf(os.Stderr, "Wrote palette to: %s\n", files[0])
	fmt.Fprintf(os.Stderr, "\n")
	fmt.Fprintf(os.Stderr, "Ptyxis watches its palette directory and picks up new\n")
	fmt.Fprintf(os.Stderr, "palettes immediately. Select 'Tinct' in:\n")
	fmt.Fprintf(os.Stderr, "  Preferences → Appearance → Palette → Tinct\n")
	fmt.Fprintf(os.Stderr, "\n")
	return nil
}

// stdLogger implements the Logger interface for template loading.
type stdLogger struct{}

func (l *stdLogger) Printf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
}

// GetMetadata returns plugin metadata.
func (p *Plugin) GetMetadata() tinctplugin.PluginInfo {
	return tinctplugin.PluginInfo{
		Name:            "ptyxis",
		Type:            "output",
		Version:         p.version,
		ProtocolVersion: tinctplugin.ProtocolVersion,
		Description:     "Generate Ptyxis terminal colour palette",
		PluginProtocol:  string(tinctplugin.PluginTypeGoPlugin),
	}
}

// GetFlagHelp returns help for plugin-specific flags.
func (p *Plugin) GetFlagHelp() []tinctplugin.FlagHelp {
	return []tinctplugin.FlagHelp{
		{
			Name:        "output-dir",
			Shorthand:   "o",
			Type:        "string",
			Default:     "auto-detected",
			Description: "Output directory (default: auto-detect native or Flatpak palette dir)",
			Required:    false,
		},
	}
}

// convertPaletteDataToThemeData converts the protocol PaletteData to colour.ThemeData.
func convertPaletteDataToThemeData(palette tinctplugin.PaletteData) *colour.ThemeData {
	colors := make(map[colour.Role]colour.ColorValue)
	indexed := make([]colour.ColorValue, 0, len(palette.AllColours))

	for roleName, cc := range palette.Colours {
		role := colour.Role(roleName)
		rgba := colour.RGBA{R: cc.RGB.R, G: cc.RGB.G, B: cc.RGB.B, A: 255}
		colors[role] = colour.NewColorValue(rgba, role, cc.Index)
	}
	for _, cc := range palette.AllColours {
		role := colour.Role(cc.Role)
		rgba := colour.RGBA{R: cc.RGB.R, G: cc.RGB.G, B: cc.RGB.B, A: 255}
		indexed = append(indexed, colour.NewColorValue(rgba, role, cc.Index))
	}

	var themeType colour.ThemeType
	if palette.ThemeType == "dark" {
		themeType = colour.ThemeDark
	} else {
		themeType = colour.ThemeLight
	}

	helper := colour.NewPaletteHelper(themeType, colors, indexed)
	return &colour.ThemeData{
		PaletteHelper: helper,
		WallpaperPath: "",
		ThemeName:     "Tinct",
	}
}
