package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	tinctplugin "github.com/jmylchreest/tinct/pkg/plugin"
	"github.com/jmylchreest/tinct/pkg/plugin/config"
	"github.com/jmylchreest/tinct/pkg/plugin/paths"
)

// Plugin implements the tinct OutputPlugin interface for keylightd-tray themes.
type Plugin struct {
	version string
	commit  string
	date    string
}

// getConfigDir returns the path to the keylightd-tray config directory.
//
// Resolution order: --keylightd-tray.output-dir flag (currently
// unsupported) → TINCT_PLUGIN_KEYLIGHTD_TRAY_OUTPUT_DIR → platform XDG
// config dir + keylightd/keylightd-tray.
func getConfigDir() string {
	fallback := filepath.Join(paths.XDGConfigDir(), "keylightd", "keylightd-tray")
	return config.Resolve("keylightd-tray", "output_dir", "", fallback)
}

// getTinctColoursPath returns the path to the tinct-colours.css file.
func getTinctColoursPath() string {
	return filepath.Join(getConfigDir(), "tinct-colours.css")
}

// getTinctCustomPath returns the path to the tinct-custom.css file.
func getTinctCustomPath() string {
	return filepath.Join(getConfigDir(), "tinct-custom.css")
}

// getCustomCSSPath returns the path to the custom.css file.
func getCustomCSSPath() string {
	return filepath.Join(getConfigDir(), "custom.css")
}

// Generate creates tinct-colours.css and tinct-custom.css files for keylightd-tray from the palette data.
func (p *Plugin) Generate(_ context.Context, palette tinctplugin.PaletteData) (map[string][]byte, error) {
	coloursPath := getTinctColoursPath()
	customPath := getTinctCustomPath()

	// Create the directory if it doesn't exist.
	outputDir := filepath.Dir(coloursPath)
	if err := os.MkdirAll(outputDir, 0o750); err != nil {
		return nil, fmt.Errorf("failed to create config directory %q: %w", outputDir, err)
	}

	// Generate CSS content.
	coloursCSS := p.generateColoursCSS(palette)
	customCSS := p.generateCustomCSS()

	if palette.Verbose {
		fmt.Fprintf(os.Stderr, "   Generating keylightd-tray theme\n")
	}

	// Check if custom.css imports tinct-custom.css and warn if not (only in verbose mode)
	p.checkImport(palette.Verbose)

	return map[string][]byte{
		coloursPath: []byte(coloursCSS),
		customPath:  []byte(customCSS),
	}, nil
}

// generateColoursCSS creates the CSS content with raw colour variable
// definitions only. Each role check is a single if; the cyclomatic
// count is inflated by the role-fallback chains (accent → accent1,
// green → accent2, etc.). A future refactor can extract a
// writeVarWithFallback helper.
//
//nolint:gocyclo // see comment above
func (p *Plugin) generateColoursCSS(palette tinctplugin.PaletteData) string {
	var sb strings.Builder

	sb.WriteString("/* Tinct-generated colours for keylightd-tray */\n")
	sb.WriteString("/* Generated by tinct-plugin-keylightd-tray */\n\n")
	sb.WriteString(":root {\n")

	// Export all palette colours as CSS variables with tinct- prefix
	// Background colors
	if bg, ok := palette.Colours["background"]; ok {
		fmt.Fprintf(&sb, "  --tinct-background: %s;\n", bg.Hex)
	}
	if fg, ok := palette.Colours["foreground"]; ok {
		fmt.Fprintf(&sb, "  --tinct-foreground: %s;\n", fg.Hex)
	}
	if surface, ok := palette.Colours["surface"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface: %s;\n", surface.Hex)
	}
	if subtle, ok := palette.Colours["subtle"]; ok {
		fmt.Fprintf(&sb, "  --tinct-subtle: %s;\n", subtle.Hex)
	}
	if overlay, ok := palette.Colours["overlay"]; ok {
		fmt.Fprintf(&sb, "  --tinct-overlay: %s;\n", overlay.Hex)
	}

	// Surface containers
	if containerLowest, ok := palette.Colours["surfaceContainerLowest"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface-container-lowest: %s;\n", containerLowest.Hex)
	}
	if containerLow, ok := palette.Colours["surfaceContainerLow"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface-container-low: %s;\n", containerLow.Hex)
	}
	if container, ok := palette.Colours["surfaceContainer"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface-container: %s;\n", container.Hex)
	}
	if containerHigh, ok := palette.Colours["surfaceContainerHigh"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface-container-high: %s;\n", containerHigh.Hex)
	}
	if containerHighest, ok := palette.Colours["surfaceContainerHighest"]; ok {
		fmt.Fprintf(&sb, "  --tinct-surface-container-highest: %s;\n", containerHighest.Hex)
	}

	// Border colors
	if borderMuted, ok := palette.Colours["borderMuted"]; ok {
		fmt.Fprintf(&sb, "  --tinct-border-muted: %s;\n", borderMuted.Hex)
	}
	if outlineVariant, ok := palette.Colours["outlineVariant"]; ok {
		fmt.Fprintf(&sb, "  --tinct-outline-variant: %s;\n", outlineVariant.Hex)
	}

	// Accent colors
	if accent, ok := palette.Colours["accent1"]; ok {
		fmt.Fprintf(&sb, "  --tinct-accent: %s;\n", accent.Hex)
	} else if accent, ok := palette.Colours["accent"]; ok {
		fmt.Fprintf(&sb, "  --tinct-accent: %s;\n", accent.Hex)
	}

	// State colors
	if green, ok := palette.Colours["green"]; ok {
		fmt.Fprintf(&sb, "  --tinct-green: %s;\n", green.Hex)
	} else if accent2, ok := palette.Colours["accent2"]; ok {
		fmt.Fprintf(&sb, "  --tinct-green: %s;\n", accent2.Hex)
	}

	if yellow, ok := palette.Colours["yellow"]; ok {
		fmt.Fprintf(&sb, "  --tinct-yellow: %s;\n", yellow.Hex)
	} else if accent3, ok := palette.Colours["accent3"]; ok {
		fmt.Fprintf(&sb, "  --tinct-yellow: %s;\n", accent3.Hex)
	}

	if red, ok := palette.Colours["red"]; ok {
		fmt.Fprintf(&sb, "  --tinct-red: %s;\n", red.Hex)
	} else if accent4, ok := palette.Colours["accent4"]; ok {
		fmt.Fprintf(&sb, "  --tinct-red: %s;\n", accent4.Hex)
	}

	sb.WriteString("}\n")

	return sb.String()
}

// generateCustomCSS creates the tinct-custom.css that imports tinct-colours.css and applies them.
func (p *Plugin) generateCustomCSS() string {
	var sb strings.Builder

	sb.WriteString("/* Tinct custom theme for keylightd-tray */\n")
	sb.WriteString("/* Import the tinct colour definitions */\n")
	sb.WriteString("@import url(\"tinct-colours.css\");\n\n")

	sb.WriteString(":root {\n")
	sb.WriteString("  /* Background colors */\n")
	sb.WriteString("  --bg-primary: var(--tinct-background);\n")
	sb.WriteString("  --bg-secondary: var(--tinct-surface);\n")
	sb.WriteString("  --bg-tertiary: var(--tinct-surface);\n")
	sb.WriteString("\n")
	sb.WriteString("  /* Text colors */\n")
	sb.WriteString("  --text-primary: var(--tinct-foreground);\n")
	sb.WriteString("  --text-secondary: var(--tinct-subtle);\n")
	sb.WriteString("  --text-muted: var(--tinct-subtle);\n")
	sb.WriteString("\n")
	sb.WriteString("  /* Accent and state colors */\n")
	sb.WriteString("  --accent: var(--tinct-accent);\n")
	sb.WriteString("  --success: var(--tinct-green);\n")
	sb.WriteString("  --warning: var(--tinct-yellow);\n")
	sb.WriteString("  --error: var(--tinct-red);\n")
	sb.WriteString("\n")
	sb.WriteString("  /* Surface colors */\n")
	sb.WriteString("  --surface: var(--tinct-surface);\n")
	sb.WriteString("  --overlay: var(--tinct-overlay);\n")
	sb.WriteString("\n")
	sb.WriteString("  /* Component-specific colors */\n")
	sb.WriteString("  --slider-track: var(--tinct-surface-container-low);\n")
	sb.WriteString("  --input-bg: var(--tinct-surface-container-lowest);\n")
	sb.WriteString("  --input-border: var(--tinct-border-muted);\n")
	sb.WriteString("  --list-item-bg: var(--tinct-surface-container-lowest);\n")
	sb.WriteString("}\n")

	return sb.String()
}

// checkImport checks if custom.css imports tinct-custom.css and prints a warning if not.
// Messages are only shown when verbose mode is enabled.
func (p *Plugin) checkImport(verbose bool) {
	if !verbose {
		return
	}

	customCSSPath := getCustomCSSPath()

	// Check if custom.css exists and contains the import.
	content, err := os.ReadFile(customCSSPath) // #nosec G304 -- Config file path from XDG config dir
	if err != nil {
		if os.IsNotExist(err) {
			// custom.css doesn't exist - prompt user to create it
			fmt.Fprintf(os.Stderr, "\n   Note: To use the tinct theme, create %s with:\n", customCSSPath)
			fmt.Fprintf(os.Stderr, "   @import url(\"tinct-custom.css\");\n\n")
		}
		return
	}

	// Check if the import statement is present
	importStatement := "@import url(\"tinct-custom.css\")"
	importStatementAlt := "@import \"tinct-custom.css\""

	if !strings.Contains(string(content), importStatement) && !strings.Contains(string(content), importStatementAlt) {
		fmt.Fprintf(os.Stderr, "\n   Note: tinct-custom.css is not imported in custom.css\n")
		fmt.Fprintf(os.Stderr, "   Add to %s:\n", customCSSPath)
		fmt.Fprintf(os.Stderr, "   @import url(\"tinct-custom.css\");\n\n")
	}
}

// PreExecute is called before Generate to perform any setup or validation.
func (p *Plugin) PreExecute(_ context.Context) (skip bool, reason string, err error) {
	// Always generate - keylightd-tray will pick up the file when it exists
	return false, "", nil
}

// PostExecute is called after files are written.
func (p *Plugin) PostExecute(_ context.Context, _ []string) error {
	// Import check is done in Generate since PostExecute stderr may not be forwarded via RPC
	return nil
}

// GetMetadata returns plugin metadata.
func (p *Plugin) GetMetadata() tinctplugin.PluginInfo {
	return tinctplugin.PluginInfo{
		Name:            "keylightd-tray",
		Type:            "output",
		Version:         p.version,
		ProtocolVersion: tinctplugin.ProtocolVersion,
		Description:     "Generate keylightd-tray custom CSS theme",
		PluginProtocol:  string(tinctplugin.PluginTypeGoPlugin),
	}
}

// GetFlagHelp returns help for plugin-specific flags.
func (p *Plugin) GetFlagHelp() []tinctplugin.FlagHelp {
	return []tinctplugin.FlagHelp{}
}
