package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	tinctplugin "github.com/jmylchreest/tinct/pkg/plugin"
)

// Plugin implements the tinct OutputPlugin interface for keylightd-tray themes.
type Plugin struct {
	version string
	commit  string
	date    string
}

// getConfigDir returns the path to the keylightd-tray config directory.
func getConfigDir() (string, error) {
	// Check XDG_CONFIG_HOME first
	configHome := os.Getenv("XDG_CONFIG_HOME")
	if configHome == "" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("failed to get home directory: %w", err)
		}
		configHome = filepath.Join(home, ".config")
	}

	return filepath.Join(configHome, "keylightd", "keylightd-tray"), nil
}

// getTinctCSSPath returns the path to the tinct-custom.css file.
func getTinctCSSPath() (string, error) {
	configDir, err := getConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "tinct-custom.css"), nil
}

// getCustomCSSPath returns the path to the custom.css file.
func getCustomCSSPath() (string, error) {
	configDir, err := getConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "custom.css"), nil
}

// Generate creates a tinct-custom.css file for keylightd-tray from the palette data.
func (p *Plugin) Generate(ctx context.Context, palette tinctplugin.PaletteData) (map[string][]byte, error) {
	outputPath, err := getTinctCSSPath()
	if err != nil {
		return nil, err
	}

	// Create the directory if it doesn't exist
	outputDir := filepath.Dir(outputPath)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create config directory %q: %w", outputDir, err)
	}

	// Generate CSS content
	css := p.generateCSS(palette)

	if palette.Verbose {
		fmt.Fprintf(os.Stderr, "   Generating keylightd-tray theme\n")
		fmt.Fprintf(os.Stderr, "   Output: %s\n", outputPath)
	}

	return map[string][]byte{
		outputPath: []byte(css),
	}, nil
}

// generateCSS creates the CSS content with theme variables.
func (p *Plugin) generateCSS(palette tinctplugin.PaletteData) string {
	var sb strings.Builder

	sb.WriteString("/* Tinct-generated theme for keylightd-tray */\n")
	sb.WriteString("/* Generated by tinct-plugin-keylightd-tray */\n\n")
	sb.WriteString(":root {\n")

	// Map palette colors to keylightd-tray CSS variables
	// Background colors
	if bg, ok := palette.Colours["background"]; ok {
		sb.WriteString(fmt.Sprintf("  --bg-primary: %s;\n", bg.Hex))
	}
	if surface, ok := palette.Colours["surface"]; ok {
		sb.WriteString(fmt.Sprintf("  --bg-secondary: %s;\n", surface.Hex))
		sb.WriteString(fmt.Sprintf("  --bg-tertiary: %s;\n", surface.Hex))
	} else if bg, ok := palette.Colours["background"]; ok {
		// Fallback: use background for secondary/tertiary
		sb.WriteString(fmt.Sprintf("  --bg-secondary: %s;\n", bg.Hex))
		sb.WriteString(fmt.Sprintf("  --bg-tertiary: %s;\n", bg.Hex))
	}

	// Text colors
	if fg, ok := palette.Colours["foreground"]; ok {
		sb.WriteString(fmt.Sprintf("  --text-primary: %s;\n", fg.Hex))
	}
	if subtle, ok := palette.Colours["subtle"]; ok {
		sb.WriteString(fmt.Sprintf("  --text-secondary: %s;\n", subtle.Hex))
		sb.WriteString(fmt.Sprintf("  --text-muted: %s;\n", subtle.Hex))
	} else if fg, ok := palette.Colours["foreground"]; ok {
		// Fallback: use foreground for secondary/muted
		sb.WriteString(fmt.Sprintf("  --text-secondary: %s;\n", fg.Hex))
		sb.WriteString(fmt.Sprintf("  --text-muted: %s;\n", fg.Hex))
	}

	// Accent color (used for sliders and interactive elements)
	if accent, ok := palette.Colours["accent1"]; ok {
		sb.WriteString(fmt.Sprintf("  --accent: %s;\n", accent.Hex))
	} else if accent, ok := palette.Colours["accent"]; ok {
		sb.WriteString(fmt.Sprintf("  --accent: %s;\n", accent.Hex))
	}

	// State colors
	if green, ok := palette.Colours["green"]; ok {
		sb.WriteString(fmt.Sprintf("  --success: %s;\n", green.Hex))
	} else if accent2, ok := palette.Colours["accent2"]; ok {
		sb.WriteString(fmt.Sprintf("  --success: %s;\n", accent2.Hex))
	}

	if yellow, ok := palette.Colours["yellow"]; ok {
		sb.WriteString(fmt.Sprintf("  --warning: %s;\n", yellow.Hex))
	} else if accent3, ok := palette.Colours["accent3"]; ok {
		sb.WriteString(fmt.Sprintf("  --warning: %s;\n", accent3.Hex))
	}

	if red, ok := palette.Colours["red"]; ok {
		sb.WriteString(fmt.Sprintf("  --error: %s;\n", red.Hex))
	} else if accent4, ok := palette.Colours["accent4"]; ok {
		sb.WriteString(fmt.Sprintf("  --error: %s;\n", accent4.Hex))
	}

	// Surface colors
	if surface, ok := palette.Colours["surface"]; ok {
		sb.WriteString(fmt.Sprintf("  --surface: %s;\n", surface.Hex))
	}
	if overlay, ok := palette.Colours["overlay"]; ok {
		sb.WriteString(fmt.Sprintf("  --overlay: %s;\n", overlay.Hex))
	} else if surface, ok := palette.Colours["surface"]; ok {
		sb.WriteString(fmt.Sprintf("  --overlay: %s;\n", surface.Hex))
	}

	sb.WriteString("\n  /* Component-specific colors */\n")

	// Slider track - use surfaceContainerLow for a muted look
	if containerLow, ok := palette.Colours["surfaceContainerLow"]; ok {
		sb.WriteString(fmt.Sprintf("  --slider-track: %s;\n", containerLow.Hex))
	} else if surface, ok := palette.Colours["surface"]; ok {
		sb.WriteString(fmt.Sprintf("  --slider-track: %s;\n", surface.Hex))
	}

	// Input background - use surfaceContainerLowest for darker/muted
	if containerLowest, ok := palette.Colours["surfaceContainerLowest"]; ok {
		sb.WriteString(fmt.Sprintf("  --input-bg: %s;\n", containerLowest.Hex))
	} else if bg, ok := palette.Colours["background"]; ok {
		sb.WriteString(fmt.Sprintf("  --input-bg: %s;\n", bg.Hex))
	}

	// Input border - use borderMuted or outlineVariant for muted borders
	if borderMuted, ok := palette.Colours["borderMuted"]; ok {
		sb.WriteString(fmt.Sprintf("  --input-border: %s;\n", borderMuted.Hex))
	} else if outlineVariant, ok := palette.Colours["outlineVariant"]; ok {
		sb.WriteString(fmt.Sprintf("  --input-border: %s;\n", outlineVariant.Hex))
	} else if surface, ok := palette.Colours["surface"]; ok {
		sb.WriteString(fmt.Sprintf("  --input-border: %s;\n", surface.Hex))
	}

	// List item background - use surfaceContainerLowest for darker/muted
	if containerLowest, ok := palette.Colours["surfaceContainerLowest"]; ok {
		sb.WriteString(fmt.Sprintf("  --list-item-bg: %s;\n", containerLowest.Hex))
	} else if bg, ok := palette.Colours["background"]; ok {
		sb.WriteString(fmt.Sprintf("  --list-item-bg: %s;\n", bg.Hex))
	}

	sb.WriteString("}\n")

	return sb.String()
}

// PreExecute is called before Generate to perform any setup or validation.
func (p *Plugin) PreExecute(ctx context.Context) (skip bool, reason string, err error) {
	// Always generate - keylightd-tray will pick up the file when it exists
	return false, "", nil
}

// PostExecute is called after files are written.
// It checks if custom.css imports tinct-custom.css and prompts the user if not.
func (p *Plugin) PostExecute(ctx context.Context, files []string) error {
	customCSSPath, err := getCustomCSSPath()
	if err != nil {
		return nil // Don't fail on path errors
	}

	// Check if custom.css exists and contains the import
	content, err := os.ReadFile(customCSSPath)
	if err != nil {
		if os.IsNotExist(err) {
			// custom.css doesn't exist - prompt user to create it
			fmt.Fprintf(os.Stderr, "\n   Note: To use the tinct theme, create %s with:\n", customCSSPath)
			fmt.Fprintf(os.Stderr, "   @import url(\"tinct-custom.css\");\n\n")
			return nil
		}
		return nil // Don't fail on read errors
	}

	// Check if the import statement is present
	importStatement := "@import url(\"tinct-custom.css\")"
	importStatementAlt := "@import \"tinct-custom.css\""

	if !strings.Contains(string(content), importStatement) && !strings.Contains(string(content), importStatementAlt) {
		fmt.Fprintf(os.Stderr, "\n   Note: tinct-custom.css is not imported in custom.css\n")
		fmt.Fprintf(os.Stderr, "   Add to %s:\n", customCSSPath)
		fmt.Fprintf(os.Stderr, "   @import url(\"tinct-custom.css\");\n\n")
	}

	return nil
}

// GetMetadata returns plugin metadata.
func (p *Plugin) GetMetadata() tinctplugin.PluginInfo {
	return tinctplugin.PluginInfo{
		Name:            "keylightd-tray",
		Type:            "output",
		Version:         p.version,
		ProtocolVersion: tinctplugin.ProtocolVersion,
		Description:     "Generate keylightd-tray custom CSS theme",
		PluginProtocol:  string(tinctplugin.PluginTypeGoPlugin),
	}
}

// GetFlagHelp returns help for plugin-specific flags.
func (p *Plugin) GetFlagHelp() []tinctplugin.FlagHelp {
	return []tinctplugin.FlagHelp{}
}
