package hyprlock

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/testing"
)

// TestHyprlockPlugin runs all standard plugin tests using shared utilities.
func TestHyprlockPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:       "hyprlock",
		ExpectedFiles:      []string{"tinct-hyprlock.conf"},
		ExpectedBinaryName: "hyprlock",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestHyprlockPlugin_ContentValidation tests hyprlock-specific content requirements.
func TestHyprlockPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-hyprlock.conf"])

	// Check for required sections
	requiredStrings := []string{
		"# Hyprlock colour theme generated by Tinct",
		"$tinct_background",
		"$tinct_foreground",
		"$tinct_accent1",
		"$tinct_background_rgba",
		"$tinct_foreground_rgba",
		"rgb(",
		"rgba(",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: dark") {
		t.Error("Generated content missing theme type")
	}
}

// TestHyprlockPlugin_GenerateWithLightTheme tests light theme generation.
func TestHyprlockPlugin_GenerateWithLightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	files, err := plugin.Generate(palette)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-hyprlock.conf"])

	// Check that theme type is present
	if !strings.Contains(content, "Detected theme: light") {
		t.Error("Generated content missing light theme type")
	}
}

// TestHyprlockPlugin_CustomOutputDir tests custom output directory handling.
func TestHyprlockPlugin_CustomOutputDir(t *testing.T) {
	plugin := New()
	plugin.outputDir = "/custom/path"

	dir := plugin.DefaultOutputDir()
	if dir != "/custom/path" {
		t.Errorf("DefaultOutputDir() = %s, want /custom/path", dir)
	}
}

// TestHyprlockPlugin_HexToRGB tests the hexToRGB helper function.
func TestHyprlockPlugin_HexToRGB(t *testing.T) {
	tests := []struct {
		name     string
		hex      string
		expected string
	}{
		{
			name:     "Standard hex with hash",
			hex:      "#1a1b26",
			expected: "1a1b26",
		},
		{
			name:     "Hex without hash",
			hex:      "c0caf5",
			expected: "c0caf5",
		},
		{
			name:     "Uppercase hex",
			hex:      "#FF6550",
			expected: "FF6550",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := hexToRGB(tt.hex)
			if result != tt.expected {
				t.Errorf("hexToRGB(%s) = %s, want %s", tt.hex, result, tt.expected)
			}
		})
	}
}

// TestHyprlockPlugin_HexToRGBA tests the hexToRGBA helper function.
func TestHyprlockPlugin_HexToRGBA(t *testing.T) {
	tests := []struct {
		name     string
		hex      string
		alpha    string
		expected string
	}{
		{
			name:     "Full opacity",
			hex:      "#1a1b26",
			alpha:    "ff",
			expected: "26, 27, 38, 1.00",
		},
		{
			name:     "Half opacity",
			hex:      "#c0caf5",
			alpha:    "80",
			expected: "192, 202, 245, 0.50",
		},
		{
			name:     "93% opacity",
			hex:      "#7aa2f7",
			alpha:    "ee",
			expected: "122, 162, 247, 0.93",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := hexToRGBA(tt.hex, tt.alpha)
			if result != tt.expected {
				t.Errorf("hexToRGBA(%s, %s) = %s, want %s", tt.hex, tt.alpha, result, tt.expected)
			}
		})
	}
}

// TestHyprlockPlugin_ThemeDataRGBMethods tests RGB helper methods.
func TestHyprlockPlugin_ThemeDataRGBMethods(t *testing.T) {
	data := ThemeData{
		Background:      "#1a1b26",
		BackgroundMuted: "#16161e",
		Foreground:      "#c0caf5",
		ForegroundMuted: "#a9b1d6",
		Accent1:         "#7aa2f7",
		Accent2:         "#bb9af7",
		Accent3:         "#7dcfff",
		Accent4:         "#9ece6a",
		Danger:          "#f7768e",
		Warning:         "#e0af68",
		Success:         "#9ece6a",
		Info:            "#7aa2f7",
	}

	tests := []struct {
		name     string
		method   func() string
		contains string
	}{
		{"BackgroundRGB", data.BackgroundRGB, "1a1b26"},
		{"BackgroundMutedRGB", data.BackgroundMutedRGB, "16161e"},
		{"ForegroundRGB", data.ForegroundRGB, "c0caf5"},
		{"ForegroundMutedRGB", data.ForegroundMutedRGB, "a9b1d6"},
		{"Accent1RGB", data.Accent1RGB, "7aa2f7"},
		{"Accent2RGB", data.Accent2RGB, "bb9af7"},
		{"Accent3RGB", data.Accent3RGB, "7dcfff"},
		{"Accent4RGB", data.Accent4RGB, "9ece6a"},
		{"DangerRGB", data.DangerRGB, "f7768e"},
		{"WarningRGB", data.WarningRGB, "e0af68"},
		{"SuccessRGB", data.SuccessRGB, "9ece6a"},
		{"InfoRGB", data.InfoRGB, "7aa2f7"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := tt.method()
			if !strings.Contains(result, tt.contains) {
				t.Errorf("%s() = %s, should contain %s", tt.name, result, tt.contains)
			}
			// Should be 6 characters (RRGGBB)
			if len(result) != 6 {
				t.Errorf("%s() = %s (length %d), want length 6", tt.name, result, len(result))
			}
		})
	}
}

// TestHyprlockPlugin_ThemeDataRGBAMethods tests RGBA helper methods.
func TestHyprlockPlugin_ThemeDataRGBAMethods(t *testing.T) {
	data := ThemeData{
		Background:      "#1a1b26",
		BackgroundMuted: "#16161e",
		Foreground:      "#c0caf5",
		ForegroundMuted: "#a9b1d6",
		Accent1:         "#7aa2f7",
		Accent2:         "#bb9af7",
		Accent3:         "#7dcfff",
		Accent4:         "#9ece6a",
		Danger:          "#f7768e",
		Warning:         "#e0af68",
		Success:         "#9ece6a",
		Info:            "#7aa2f7",
	}

	tests := []struct {
		name   string
		method func(string) string
		alpha  string
	}{
		{"BackgroundRGBA", data.BackgroundRGBA, "ee"},
		{"BackgroundMutedRGBA", data.BackgroundMutedRGBA, "cc"},
		{"ForegroundRGBA", data.ForegroundRGBA, "ff"},
		{"ForegroundMutedRGBA", data.ForegroundMutedRGBA, "dd"},
		{"Accent1RGBA", data.Accent1RGBA, "ff"},
		{"Accent2RGBA", data.Accent2RGBA, "ff"},
		{"Accent3RGBA", data.Accent3RGBA, "ff"},
		{"Accent4RGBA", data.Accent4RGBA, "ff"},
		{"DangerRGBA", data.DangerRGBA, "ff"},
		{"WarningRGBA", data.WarningRGBA, "ff"},
		{"SuccessRGBA", data.SuccessRGBA, "ff"},
		{"InfoRGBA", data.InfoRGBA, "ff"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := tt.method(tt.alpha)
			// Should contain comma-separated values
			if !strings.Contains(result, ",") {
				t.Errorf("%s(%s) = %s, should contain commas", tt.name, tt.alpha, result)
			}
			// Should have 4 parts (R, G, B, A)
			parts := strings.Split(result, ",")
			if len(parts) != 4 {
				t.Errorf("%s(%s) = %s, should have 4 comma-separated parts", tt.name, tt.alpha, result)
			}
		})
	}
}

// TestHyprlockPlugin_PrepareThemeData tests theme data preparation.
func TestHyprlockPlugin_PrepareThemeData(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	data := plugin.prepareThemeData(palette)

	// Check that all fields are populated
	if data.SourceTheme == "" {
		t.Error("SourceTheme should not be empty")
	}
	if data.Background == "" {
		t.Error("Background should not be empty")
	}
	if data.Foreground == "" {
		t.Error("Foreground should not be empty")
	}
	if data.Accent1 == "" {
		t.Error("Accent1 should not be empty")
	}

	// Check that theme type matches
	if data.SourceTheme != "dark" {
		t.Errorf("SourceTheme = %s, want dark", data.SourceTheme)
	}
}

// TestHyprlockPlugin_GetEmbeddedTemplates tests embedded template access.
func TestHyprlockPlugin_GetEmbeddedTemplates(t *testing.T) {
	fs := GetEmbeddedTemplates()

	entries, err := fs.ReadDir(".")
	if err != nil {
		t.Fatalf("ReadDir() error = %v", err)
	}

	found := false
	for _, entry := range entries {
		if entry.Name() == "tinct.conf.tmpl" {
			found = true
			break
		}
	}

	if !found {
		t.Error("Template file tinct.conf.tmpl not found in embedded filesystem")
	}
}
