import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for tinct documentation.
 * Organized by outcome (what users want to accomplish) rather than just reference.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'installation',
    'telemetry',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'quickstart/index',
        'quickstart/first-theme',
        'quickstart/workflows',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/color-extraction',
        'concepts/material-design',
        'concepts/color-roles',
        'concepts/theme-detection',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      link: {
        type: 'doc',
        id: 'commands/index',
      },
      items: [
        'commands/generate',
        'commands/extract',
        'commands/plugins',
        'commands/files',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/overview',
      },
      items: [
        // Input Plugins — manual category wraps the autogenerated
        // list so it renders as a collapsible header (peer to "Output
        // Plugins"). Uses generated-index instead of a doc link
        // because Docusaurus's `link: {type: doc}` dedup doesn't fire
        // when the items array contains an autogenerated entry — the
        // linked index.md would appear duplicated as a sibling of the
        // plugin pages. generated-index sidesteps that by having
        // Docusaurus build the landing page from the category itself.
        {
          type: 'category',
          label: 'Input Plugins',
          link: {
            type: 'generated-index',
            title: 'Input plugins',
            description:
              'Input plugins extract or generate colour palettes from various sources — images, files, URLs, or AI services.',
            slug: '/plugins/input',
          },
          items: [{type: 'autogenerated', dirName: 'plugins/input'}],
        },
        {
          type: 'category',
          label: 'Output Plugins',
          link: {
            type: 'doc',
            id: 'plugins/output/index',
          },
          items: [
            {
              type: 'category',
              label: 'Terminals',
              items: [{type: 'autogenerated', dirName: 'plugins/output/terminals'}],
            },
            {
              type: 'category',
              label: 'Desktop Environments',
              items: [{type: 'autogenerated', dirName: 'plugins/output/desktop'}],
            },
            {
              type: 'category',
              label: 'Hyprland Ecosystem',
              items: [{type: 'autogenerated', dirName: 'plugins/output/hyprland'}],
            },
            {
              type: 'category',
              label: 'Bars & Launchers',
              items: [{type: 'autogenerated', dirName: 'plugins/output/bars-launchers'}],
            },
            {
              type: 'category',
              label: 'Editors & Multiplexers',
              items: [{type: 'autogenerated', dirName: 'plugins/output/editors'}],
            },
            {
              type: 'category',
              label: 'Special Purpose',
              items: [{type: 'autogenerated', dirName: 'plugins/output/special'}],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Templating',
      link: {
        type: 'doc',
        id: 'templating/index',
      },
      items: [
        'templating/functions',
        'templating/color-access',
        'templating/format-conversion',
        'templating/versioned',
      ],
    },
    {
      type: 'category',
      label: 'Plugin Development',
      link: {
        type: 'doc',
        id: 'plugin-development/index',
      },
      items: [
        'plugin-development/protocols',
        'plugin-development/creating',
        'plugin-development/hooks',
        'plugin-development/publishing',
      ],
    },
    // Changelog is a single Keep-a-Changelog file maintained at
    // CHANGELOG.md and mirrored to docs/docs/changelog.md by the
    // release workflow. The previous per-version split (changelog/
    // directory with index.md + v*.md entries) duplicated routes with
    // changelog.md and is no longer maintained.
    'changelog',
  ],
};

export default sidebars;
