import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for tinct documentation.
 * Organized by outcome (what users want to accomplish) rather than just reference.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'installation',
    'telemetry',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'quickstart/index',
        'quickstart/first-theme',
        'quickstart/workflows',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/color-extraction',
        'concepts/material-design',
        'concepts/color-roles',
        'concepts/theme-detection',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      link: {
        type: 'doc',
        id: 'commands/index',
      },
      items: [
        'commands/generate',
        'commands/extract',
        'commands/plugins',
        'commands/files',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/overview',
      },
      items: [
        // Input Plugins — category metadata lives in
        // docs/plugins/input/_category_.json so Docusaurus
        // auto-excludes index.md (the linked landing page) from the
        // autogenerated sibling list. Order driven by each plugin
        // README's frontmatter sidebar_position.
        {type: 'autogenerated', dirName: 'plugins/input'},
        {
          type: 'category',
          label: 'Output Plugins',
          link: {
            type: 'doc',
            id: 'plugins/output/index',
          },
          items: [
            {
              type: 'category',
              label: 'Terminals',
              items: [{type: 'autogenerated', dirName: 'plugins/output/terminals'}],
            },
            {
              type: 'category',
              label: 'Desktop Environments',
              items: [{type: 'autogenerated', dirName: 'plugins/output/desktop'}],
            },
            {
              type: 'category',
              label: 'Hyprland Ecosystem',
              items: [{type: 'autogenerated', dirName: 'plugins/output/hyprland'}],
            },
            {
              type: 'category',
              label: 'Bars & Launchers',
              items: [{type: 'autogenerated', dirName: 'plugins/output/bars-launchers'}],
            },
            {
              type: 'category',
              label: 'Editors & Multiplexers',
              items: [{type: 'autogenerated', dirName: 'plugins/output/editors'}],
            },
            {
              type: 'category',
              label: 'Special Purpose',
              items: [{type: 'autogenerated', dirName: 'plugins/output/special'}],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Templating',
      link: {
        type: 'doc',
        id: 'templating/index',
      },
      items: [
        'templating/functions',
        'templating/color-access',
        'templating/format-conversion',
        'templating/versioned',
      ],
    },
    {
      type: 'category',
      label: 'Plugin Development',
      link: {
        type: 'doc',
        id: 'plugin-development/index',
      },
      items: [
        'plugin-development/protocols',
        'plugin-development/creating',
        'plugin-development/hooks',
        'plugin-development/publishing',
      ],
    },
    // Changelog is a single Keep-a-Changelog file maintained at
    // CHANGELOG.md and mirrored to docs/docs/changelog.md by the
    // release workflow. The previous per-version split (changelog/
    // directory with index.md + v*.md entries) duplicated routes with
    // changelog.md and is no longer maintained.
    'changelog',
  ],
};

export default sidebars;
