import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Single source of truth for output plugin categories — shared with
// docs/scripts/sync-plugin-readmes.mjs and cmd/tinct-check-readmes.
// Adding a new category is one JSON edit and a `tinct generate` run.
const outputCategories: {id: string; label: string}[] = require('../internal/plugin/output/categories.json');

/**
 * Sidebar configuration for tinct documentation.
 * Organized by outcome (what users want to accomplish) rather than just reference.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    'installation',
    'telemetry',
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'quickstart/index',
        'quickstart/first-theme',
        'quickstart/workflows',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      items: [
        'concepts/color-extraction',
        'concepts/material-design',
        'concepts/color-roles',
        'concepts/theme-detection',
      ],
    },
    {
      type: 'category',
      label: 'Commands',
      link: {
        type: 'doc',
        id: 'commands/index',
      },
      items: [
        'commands/generate',
        'commands/extract',
        'commands/plugins',
        'commands/files',
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      link: {
        type: 'doc',
        id: 'plugins/overview',
      },
      items: [
        // Input Plugins — manual items list matches the Output Plugins
        // pattern (collapsible category with hand-written landing
        // page). The autogenerated variant would either duplicate the
        // landing as a sibling or replace it with a Docusaurus card
        // list; neither matches Output's UX. Trade-off: adding a new
        // input plugin needs a sidebar edit, but input plugins are a
        // small fixed set so the churn is minimal.
        {
          type: 'category',
          label: 'Input Plugins',
          link: {type: 'doc', id: 'plugins/input/index'},
          items: [
            'plugins/input/image',
            'plugins/input/google-genai',
            'plugins/input/openrouter',
            'plugins/input/remote-json',
            'plugins/input/remote-css',
            'plugins/input/file',
            'plugins/input/markdown',
          ],
        },
        {
          type: 'category',
          label: 'Output Plugins',
          link: {
            type: 'doc',
            id: 'plugins/output/index',
          },
          // Sub-categories built from categories.json — adding a new
          // entry to that file picks it up here automatically (no
          // sidebar edit needed beyond ensuring the dir exists in
          // docs/docs/plugins/output/).
          items: outputCategories.map((c) => ({
            type: 'category' as const,
            label: c.label,
            items: [{type: 'autogenerated' as const, dirName: `plugins/output/${c.id}`}],
          })),
        },
      ],
    },
    {
      type: 'category',
      label: 'Templating',
      link: {
        type: 'doc',
        id: 'templating/index',
      },
      items: [
        'templating/functions',
        'templating/color-access',
        'templating/format-conversion',
        'templating/versioned',
      ],
    },
    {
      type: 'category',
      label: 'Plugin Development',
      link: {
        type: 'doc',
        id: 'plugin-development/index',
      },
      items: [
        'plugin-development/protocols',
        'plugin-development/creating',
        'plugin-development/hooks',
        'plugin-development/publishing',
      ],
    },
    // Changelog is a single Keep-a-Changelog file maintained at
    // CHANGELOG.md and mirrored to docs/docs/changelog.md by the
    // release workflow. The previous per-version split (changelog/
    // directory with index.md + v*.md entries) duplicated routes with
    // changelog.md and is no longer maintained.
    'changelog',
  ],
};

export default sidebars;
