package awww

import (
	"strings"
	"testing"

	"github.com/jmylchreest/tinct/internal/colour"
	plugintesting "github.com/jmylchreest/tinct/internal/plugin/output/shared/testing"
)

// TestAwwwPlugin runs all standard plugin tests using shared utilities.
func TestAwwwPlugin(t *testing.T) {
	plugin := New()

	config := plugintesting.TestConfig{
		ExpectedName:         "awww",
		ExpectedFiles:        []string{"tinct-awww.sh"},
		ExpectedBinaryName:   "awww",
		ExpectedDirSubstring: "awww",
	}

	plugintesting.RunAllTests(t, plugin, config)
}

// TestAwwwPlugin_ContentValidation tests awww-specific content requirements.
func TestAwwwPlugin_ContentValidation(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-awww.sh"])

	// Check for required content.
	requiredStrings := []string{
		"#!/bin/sh",
		"awww wallpaper configuration generated by Tinct",
		"awww",
		"transition",
		"clear",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content missing required string: %s", required)
		}
	}
}

// TestAwwwPlugin_ContentWithWallpaper tests content when a wallpaper path is provided.
func TestAwwwPlugin_ContentWithWallpaper(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()

	themeData := colour.NewThemeData(palette, "/home/user/wallpaper.jpg", "/home/user/wallpaper.jpg", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-awww.sh"])

	// Check for wallpaper-specific content.
	requiredStrings := []string{
		"/home/user/wallpaper.jpg",
		"TINCT_AWWW_WALLPAPER=",
		"transition-type",
		"transition-step",
		"transition-fps",
	}

	for _, required := range requiredStrings {
		if !strings.Contains(content, required) {
			t.Errorf("Generated content with wallpaper missing required string: %s", required)
		}
	}
}

// TestAwwwPlugin_TransitionOptions tests custom transition options.
func TestAwwwPlugin_TransitionOptions(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeDark)
	plugin := New()
	plugin.transitionType = "center"
	plugin.transitionStep = "90"
	plugin.transitionFPS = "60"

	themeData := colour.NewThemeData(palette, "/home/user/wallpaper.jpg", "/home/user/wallpaper.jpg", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	content := string(files["tinct-awww.sh"])

	if !strings.Contains(content, "center") {
		t.Error("Generated content should contain transition type 'center'")
	}
	if !strings.Contains(content, "90") {
		t.Error("Generated content should contain transition step '90'")
	}
	if !strings.Contains(content, "60") {
		t.Error("Generated content should contain transition FPS '60'")
	}
}

// TestAwwwPlugin_LightTheme tests generation with a light theme.
func TestAwwwPlugin_LightTheme(t *testing.T) {
	palette := plugintesting.CreateTestPalette(colour.ThemeLight)
	plugin := New()

	themeData := colour.NewThemeData(palette, "", "", "")
	files, err := plugin.Generate(themeData)
	if err != nil {
		t.Fatalf("Generate() error = %v", err)
	}

	if len(files) == 0 {
		t.Error("Generate() returned no files for light theme")
	}
}
